// Loads the data extracted from the ROM by tools/export_assets.py.

import { runVramScript } from './vramscript.js';

// Resolved against THIS MODULE's url, not the document's. A bare '../assets/'
// is resolved relative to the page, so it only works when the page happens to
// sit one level above src/ -- it breaks the moment the launcher moves.
const BASE = new URL('../assets/', import.meta.url).href;

let manifest = null;
const levelCache = new Map();
let playerTiles = null;

/**
 * The build id this code was deployed with, or null in a dev tree.
 *
 * src/buildid.js is generated by tools/build-dist.mjs and does not exist when
 * serving the repo directly, so the import is allowed to fail.
 */
async function deployedBuildId() {
  try {
    const m = await import('./buildid.js');
    return m.BUILD_ID ?? null;
  } catch {
    return null;                       // dev tree: nothing to check against
  }
}

export async function loadManifest() {
  if (!manifest) {
    const r = await fetch(BASE + 'manifest.json');
    if (!r.ok) throw new Error(`assets/manifest.json missing (${r.status}) - run: python tools/export_assets.py`);
    manifest = await r.json();

    // Catch a MIXED deploy: new code against an old manifest, or the reverse.
    // Every path is served no-cache and does revalidate, but deploys are not
    // atomic from a browser's point of view -- a page loaded while one lands
    // can take its JS from one edge and its assets from another. That is what
    // "cannot read properties of undefined (reading 'map')" on a phone was,
    // and it is invisible unless something compares the two halves.
    const code = await deployedBuildId();
    const assets = manifest.buildId;
    if (code && assets && code !== assets) {
      manifest = null;                 // do not cache a mismatched pair
      throw new Error(
        `stale copy: this page's code is build ${code} but assets/manifest.json `
        + `is build ${assets}. Reload the page to pick up a matching pair.`);
    }
  }
  return manifest;
}

export async function loadPlayerTiles() {
  if (!playerTiles) {
    const r = await fetch(BASE + 'player.tiles.bin');
    // Only loadManifest above used to check r.ok. A 404 here yields an EMPTY
    // ArrayBuffer, so the OBJ tile pool comes out zero-filled and the game
    // draws a WRONG PICTURE rather than throwing -- which is exactly how a
    // moved assets/ tree can stay bit-exact under every headless harness (they
    // compare state, not the tile bytes they never loaded) and be broken in the
    // browser. Fail loudly and name the file.
    if (!r.ok) throw new Error(`assets/player.tiles.bin missing (${r.status}) - run: python tools/export_assets.py`);
    playerTiles = new Uint8Array(await r.arrayBuffer());
  }
  return playerTiles;
}

/**
 * @returns {{info:object, cells:Uint8Array, vram:Uint8Array}}
 *   cells = the $D000 image (2 B/cell, column-major, 16 rows per column)
 *   vram  = the $8000-$9FFF image after the level's resource loads
 */
export async function loadLevel(n) {
  if (levelCache.has(n)) return levelCache.get(n);
  const m = await loadManifest();
  const pad = String(n).padStart(2, '0');

  // Same as loadPlayerTiles: a 404 without this check gives a zero-filled
  // $D000 image and a zero-filled $8000-$9FFF, i.e. an empty level that RENDERS
  // instead of an error that names the file.
  const grab = async (name) => {
    const r = await fetch(`${BASE}levels/${name}`);
    if (!r.ok) throw new Error(`assets/levels/${name} missing (${r.status}) - run: python tools/export_assets.py`);
    return r.arrayBuffer();
  };
  const [cellsBuf, vramBuf] = await Promise.all([
    grab(`${pad}.map.bin`),
    grab(`${pad}.vram.bin`),
  ]);

  const out = {
    info: m.levels[n - 1],
    cells: new Uint8Array(cellsBuf),
    vram: new Uint8Array(vramBuf),
  };
  levelCache.set(n, out);
  return out;
}

/**
 * Decode one 2bpp tile into 64 palette indices (0-3).
 * BG/window tiles use the SIGNED $8800 region because the game writes
 * rLCDC = $E7 at every site (master reference §7.1).
 */
export function decodeTile(vram, addr) {
  const out = new Uint8Array(64);
  const base = addr - 0x8000;
  for (let y = 0; y < 8; y++) {
    const lo = vram[base + y * 2];
    const hi = vram[base + y * 2 + 1];
    for (let x = 0; x < 8; x++) {
      const b = 7 - x;
      out[y * 8 + x] = ((lo >> b) & 1) | (((hi >> b) & 1) << 1);
    }
  }
  return out;
}

/** Decode a 2bpp tile straight out of a raw buffer at a byte offset. */
export function decodeTileBuf(buf, offset) {
  const out = new Uint8Array(64);
  for (let y = 0; y < 8; y++) {
    const lo = buf[offset + y * 2];
    const hi = buf[offset + y * 2 + 1];
    for (let x = 0; x < 8; x++) {
      const b = 7 - x;
      out[y * 8 + x] = ((lo >> b) & 1) | (((hi >> b) & 1) << 1);
    }
  }
  return out;
}

/**
 * STATIC BG ART: the two init-time VRAM scripts that paint straight into the
 * $9800 tilemap and are never streamed over.
 *
 *   $0E94  levels 9/$0A/$0B  7:$7A5E  -> $9800-$98FF, tilemap rows 0-7
 *          the city skyline the parallax sky scrolls behind.
 *   $0EF8  level 6 only      7:$7B77  -> $9A6D-$9B70, tilemap rows 19-27
 *          the train's track band.
 *
 * renderer.js samples the level map through the metatile table rather than
 * modelling the column streamer, which is exactly equivalent for every cell the
 * streamer wrote and blind to every cell it did not.  These are the cells it
 * did not: measured with tools/oracle/tilemapdump.py, 168 of 378 visible cells
 * on each of 9/10/11 and 103 of 378 on level 6.
 *
 * The result is indexed in TILEMAP space -- (row, col) of the 32x32 $9800 map,
 * i.e. ((worldY >> 3) & 31) * 32 + ((worldX >> 3) & 31).  That is not a detail:
 * on level 6 the band is displayed through the mode-0/1 raster arm, whose SCX
 * is $FFCC rather than the camera, so a world-space lookup would slide the
 * track sideways relative to the cells the hardware actually reads.
 *
 * @returns Int16Array(1024), -1 where the script writes nothing, or null.
 */
const bgArtCache = new Map();
export function bgArtForLevel(n) {
  if (bgArtCache.has(n)) return bgArtCache.get(n);
  // Do not cache a miss taken before loadManifest() resolved: every render
  // path awaits initLevel first, but a caller that does not must not be
  // permanently poisoned into "this level has no art".
  if (!manifest) return null;
  let out = null;
  const entries = manifest.bgArt || [];
  for (const e of entries) {
    if (!e.levels.includes(n)) continue;
    if (!out) { out = new Int16Array(1024); out.fill(-1); }
    // A full 8 KB window so a script that writes outside $9800-$9BFF (none
    // does today) is dropped by the range test below rather than aliased in.
    const vram = new Uint8Array(0x2000);
    runVramScript(vram, decodeB64(e.script), {
      onWrite: (addr, v) => {
        const i = addr - 0x9800;
        if (i >= 0 && i < 1024) out[i] = v;
      },
    });
  }
  bgArtCache.set(n, out);
  return out;
}

function decodeB64(s) {
  const bin = typeof atob === 'function'
    ? atob(s)
    : Buffer.from(s, 'base64').toString('binary');
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const bgTileAddr = (id) => (id < 0x80 ? 0x9000 + id * 16 : 0x8800 + (id - 0x80) * 16);
export const objTileAddr = (id) => 0x8000 + id * 16;

/** Pre-decode every BG and OBJ tile once per level: 384 + 256 tiles. */
export function buildTileCache(vram) {
  const bg = new Array(256);
  for (let i = 0; i < 256; i++) bg[i] = decodeTile(vram, bgTileAddr(i));
  const obj = new Array(256);
  for (let i = 0; i < 256; i++) obj[i] = decodeTile(vram, objTileAddr(i));
  return { bg, obj };
}
