#!/usr/bin/env python3
r"""WAVE 4 -- export the ROM tables the player port reads, from the DECRYPTED
:maincpu image, into `games/ddpdoj/rip/port/` (gitignored, twice over).

NOTHING ROM-DERIVED IS EVER COMMITTED (docs/worklog/README.md rule 1).  The
port's *code* is ours and is committed; the numbers it indexes are the
cartridge's and are regenerated by this tool from a ROM the runner owns.

Every table below is cited by ROM address and by the instruction that reads it,
so a second person can check any entry without re-deriving the addressing:

  $2552DC  16 bytes   stick nibble -> ANGLE byte.  Read at $2495B4
                      `move.b (A2,D0.w),($1b,A6)` with D0 = ($18,A6) & $f.
                      $FF = "no direction" (the `bpl` at $2495BA takes the
                      no-move path).  MEASURED values: ff 00 20 ff 30 38 28 ff
                      10 08 18 ff ff ff ff ff.
  $2418B4  256 words  ANGLE-FOLD table.  Read at $241830
                      `adda.w (A0,D3.w),A3` with D3 = (angle & $3f) * 8, i.e.
                      word index angle*4.  It is a triangle wave 0,8,...,$200,
                      $1F8,...,0 -- it folds the full circle onto ONE quadrant
                      of 65 entries, which is why the quadrant negation at
                      $241850/$241870/$241890/$2418B0 is not a double count.
  $200920  N longs    SPEED-LEVEL pointer table.  Read at $241820
                      `movea.l (A3,D0.w),A3` with D0 = speedIndex * 4.
                      Entry s points at $200D20 + $208*s.
  ...each              65 entries x {dx:int32, dy:int32}, ONE QUADRANT, 0 deg
                      (dx=r, dy=0) to 90 deg (dx=0, dy=r).  Read at $241836
                      `move.l (A3)+,D2 / move.l (A3)+,D3`, then `asr.l #4`.
                      Speed 0's table is all zeros (a real "do not move").
  $2552EC  16 bytes   the knockback ramp read at $2496B2 `move.w (A0,D0.w),D0`
                      with D0 = ($46,A6).  Only reached when bit 7 of the
                      player's ($1,A6) is set; UNPORTED path, exported for the
                      record.
  $25533A / $2553CA   the two ANIMATION pointer tables read at the handler's
                      tail $249E4E: `movea.l (A0,D0.w),A0` with D0 =
                      shipType*2, then `move.l (A0,D0.w),($a,A6)` with
                      D0 = tilt ($4e,A6), which steps by 4 over [-$20,+$20].
                      So 17 longs centred on the pointer.

  python export-tables.py            write rip/port/player.tables.json
  python export-tables.py --verify   re-read and check the invariants only
"""
from __future__ import annotations

import hashlib
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IMAGE = HERE / "oracle" / "out" / "maincpu.bin"
OUT = HERE.parent / "rip" / "port"

DIR_TABLE = 0x2552DC          # 16 bytes
FOLD_TABLE = 0x2418B4         # 256 words
SPEED_PTRS = 0x200920         # longs
QUAD_ENTRIES = 65             # 0..90 degrees inclusive
QUAD_STRIDE = QUAD_ENTRIES * 8    # $208
KNOCKBACK = 0x2552EC          # 16 bytes
# The frame-rate GOVERNOR's four PC-relative word tables, read at $23C2B4 /
# $23C2E4 (pairs indexed by $813096) and $23C342 / $23C332 (single words indexed
# by $813094).  See src/framesync.js.
GOV_TABLES = {"t23C3EE": (0x23C3EE, 10), "t23C402": (0x23C402, 10),
              "t23C416": (0x23C416, 5), "t23C420": (0x23C420, 5)}
ANIM_A = 0x25533A
ANIM_B = 0x2553CA
TILT_MIN, TILT_MAX, TILT_STEP = -0x20, 0x20, 4
SCAN_CAP = 64                 # see speed_levels(): a scan cap, not the table end


def u16(d: bytes, a: int) -> int:
    return struct.unpack_from(">H", d, a)[0]


def u32(d: bytes, a: int) -> int:
    return struct.unpack_from(">I", d, a)[0]


def i32(d: bytes, a: int) -> int:
    return struct.unpack_from(">i", d, a)[0]


def speed_levels(d: bytes) -> int:
    """How many speed levels the pointer table holds.

    NOT a guess: entry s must be exactly $200D20 + $208*s.  The count is where
    that stops holding.  MEASURED: the pattern still holds at s = 64, so the
    real table is at least that long and this is a SCAN CAP, not the end of the
    table -- said out loud because "64 levels" would otherwise read as a fact
    about the ROM.  The highest index the game was ever OBSERVED to use is 28
    (Button 2 held, worklog 04); the cap is well clear of it and the port throws
    by name on any index it did not export rather than reading past the array.
    """
    base = u32(d, SPEED_PTRS)
    n = 0
    while n < SCAN_CAP and u32(d, SPEED_PTRS + 4 * n) == base + QUAD_STRIDE * n:
        n += 1
    return n


def build(d: bytes) -> dict:
    n = speed_levels(d)
    base = u32(d, SPEED_PTRS)
    quads = []
    for s in range(n):
        a = base + QUAD_STRIDE * s
        quads.append([[i32(d, a + 8 * i), i32(d, a + 8 * i + 4)]
                      for i in range(QUAD_ENTRIES)])

    def anim(tbl: int, idx: int) -> list[list[int]]:
        # LITERALLY as the ROM addresses it: `move.w ($58,A6),D0 / add.w D0,D0 /
        # movea.l (A0,D0.w),A0`.  Note the consequence, which is why only index
        # 0 is exported: with ($58,A6) = 1 the longword read is at tbl+2 and
        # lands MIDWAY through the first pointer.  The two pointers here are 4
        # bytes apart, so the ship selector must be 0 or 2, not 0 or 1 -- and
        # ($58,A6) was MEASURED to be 0 for TYPE-A over the whole corpus.
        # TYPE-B was never exercised, so the port throws rather than guess.
        ptr = u32(d, tbl + idx * 2)
        return [[u16(d, ptr + t), u16(d, ptr + t + 2)]
                for t in range(TILT_MIN, TILT_MAX + 1, TILT_STEP)]

    return {
        "_note": ("ROM-DERIVED. Regenerate with games/ddpdoj/tools/export-tables.py. "
                  "Never commit this file."),
        "set": "ddpdojblk", "build": "B",
        "image_sha256": hashlib.sha256(d).hexdigest(),
        "dirTable": {"rom": f"${DIR_TABLE:06X}",
                     "bytes": list(d[DIR_TABLE:DIR_TABLE + 16])},
        "foldTable": {"rom": f"${FOLD_TABLE:06X}",
                      "words": [u16(d, FOLD_TABLE + 2 * i) for i in range(256)]},
        "knockback": {"rom": f"${KNOCKBACK:06X}",
                      "words": [u16(d, KNOCKBACK + 2 * i) for i in range(8)]},
        "speed": {"rom": f"${SPEED_PTRS:06X}", "levels": n,
                  "quadBase": f"${base:06X}", "quadStride": QUAD_STRIDE,
                  "quadEntries": QUAD_ENTRIES, "quads": quads},
        "gov": {k: {"rom": f"${a:06X}",
                    "words": [u16(d, a + 2 * i) for i in range(n)]}
                for k, (a, n) in GOV_TABLES.items()},
        "anim": {"tiltMin": TILT_MIN, "tiltStep": TILT_STEP,
                 "a": {"rom": f"${ANIM_A:06X}", "shipSel0": anim(ANIM_A, 0)},
                 "b": {"rom": f"${ANIM_B:06X}", "shipSel0": anim(ANIM_B, 0)}},
    }


def verify(t: dict) -> list[str]:
    """The invariants the PORT depends on.  A table that silently changed shape
    must stop the port, not feed it plausible numbers."""
    bad = []
    dt = t["dirTable"]["bytes"]
    if len(dt) != 16:
        bad.append("dirTable is not 16 bytes")
    for i, v in enumerate(dt):
        if v != 0xFF and (v & 0x07):
            bad.append(f"dirTable[{i}]=${v:02X} is not a multiple of 8")
    fold = t["foldTable"]["words"]
    if len(fold) != 256:
        bad.append("foldTable is not 256 words")
    # the triangle: index a*4 for a in 0..63 must fold into [0, $200]
    for a in range(64):
        if not 0 <= fold[a * 4] <= 0x200:
            bad.append(f"foldTable[{a * 4}]=${fold[a * 4]:04X} escapes the quadrant")
    sp = t["speed"]
    if sp["levels"] < 29:
        bad.append(f"only {sp['levels']} speed levels, but index 28 is MEASURED in "
                   f"use (Button 2 held; see 04-impl worklog)")
    for s, q in enumerate(sp["quads"]):
        if len(q) != QUAD_ENTRIES:
            bad.append(f"speed {s}: {len(q)} entries, expected {QUAD_ENTRIES}")
            continue
        if q[0][1] != 0 or q[-1][0] != 0:
            bad.append(f"speed {s}: quadrant does not run (r,0)..(0,r): "
                       f"{q[0]} .. {q[-1]}")
    if sp["quads"][0] != [[0, 0]] * QUAD_ENTRIES:
        bad.append("speed level 0 is not all zeros -- it is the game's 'do not move'")
    for k, (a, n) in GOV_TABLES.items():
        if len(t["gov"][k]["words"]) != n:
            bad.append(f"gov table {k} is not {n} words")
    for k in ("a", "b"):
        n = len(t["anim"][k]["shipSel0"])
        if n != (TILT_MAX - TILT_MIN) // TILT_STEP + 1:
            bad.append(f"anim {k}: {n} tilt entries, expected 17")
    return bad


def main() -> int:
    if not IMAGE.exists():
        raise SystemExit(f"{IMAGE} missing -- run `python tools/oracle/derive.py` first")
    d = IMAGE.read_bytes()
    t = build(d)
    bad = verify(t)
    for b in bad:
        print("FAIL " + b, file=sys.stderr)
    if bad:
        return 1
    print(f"  image sha256 {t['image_sha256']}")
    print(f"  dirTable   {' '.join(f'{b:02x}' for b in t['dirTable']['bytes'])}")
    print(f"  speed      {t['speed']['levels']} levels at {t['speed']['quadBase']}"
          f" stride ${t['speed']['quadStride']:X}, {QUAD_ENTRIES} entries each")
    for s in (0, 1, 22, 28):
        if s < t["speed"]["levels"]:
            q = t["speed"]["quads"][s]
            print(f"    level {s:2d}: 0deg=({q[0][0] >> 4},{q[0][1] >> 4})"
                  f"  45deg=({q[32][0] >> 4},{q[32][1] >> 4})"
                  f"  90deg=({q[64][0] >> 4},{q[64][1] >> 4})   [after asr.l #4]")
    if "--verify" in sys.argv:
        print("  VERIFY OK")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / ".gitignore").write_text("*\n", encoding="utf8")
    p = OUT / "player.tables.json"
    p.write_text(json.dumps(t), encoding="utf8")
    print(f"  wrote {p}  ({p.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
