#!/usr/bin/env python3
r"""WAVE 4 -- export the ROM tables the player port reads, from the DECRYPTED
:maincpu image, into `games/ddpdoj/rip/port/` (gitignored, twice over).

NOTHING ROM-DERIVED IS EVER COMMITTED (docs/worklog/README.md rule 1).  The
port's *code* is ours and is committed; the numbers it indexes are the
cartridge's and are regenerated by this tool from a ROM the runner owns.

Every table below is cited by ROM address and by the instruction that reads it,
so a second person can check any entry without re-deriving the addressing:

  $2552DC  16 bytes   stick nibble -> ANGLE byte.  Read at $2495B4
                      `move.b (A2,D0.w),($1b,A6)` with D0 = ($18,A6) & $f.
                      $FF = "no direction" (the `bpl` at $2495BA takes the
                      no-move path).  MEASURED values: ff 00 20 ff 30 38 28 ff
                      10 08 18 ff ff ff ff ff.
  $2418B4  256 words  ANGLE-FOLD table.  Read at $241830
                      `adda.w (A0,D3.w),A3` with D3 = (angle & $3f) * 8, i.e.
                      word index angle*4.  It is a triangle wave 0,8,...,$200,
                      $1F8,...,0 -- it folds the full circle onto ONE quadrant
                      of 65 entries, which is why the quadrant negation at
                      $241850/$241870/$241890/$2418B0 is not a double count.
  $200920  N longs    SPEED-LEVEL pointer table.  Read at $241820
                      `movea.l (A3,D0.w),A3` with D0 = speedIndex * 4.
                      Entry s points at $200D20 + $208*s.
  ...each              65 entries x {dx:int32, dy:int32}, ONE QUADRANT, 0 deg
                      (dx=r, dy=0) to 90 deg (dx=0, dy=r).  Read at $241836
                      `move.l (A3)+,D2 / move.l (A3)+,D3`, then `asr.l #4`.
                      Speed 0's table is all zeros (a real "do not move").
  $2552EC  16 bytes   the knockback ramp read at $2496B2 `move.w (A0,D0.w),D0`
                      with D0 = ($46,A6).  Only reached when bit 7 of the
                      player's ($1,A6) is set; UNPORTED path, exported for the
                      record.
  $25533A / $2553CA   the two ANIMATION pointer tables read at the handler's
                      tail $249E4E: `movea.l (A0,D0.w),A0` with D0 =
                      shipType*2, then `move.l (A0,D0.w),($a,A6)` with
                      D0 = tilt ($4e,A6), which steps by 4 over [-$20,+$20].
                      So 17 longs centred on the pointer.

  python export-tables.py            write rip/port/player.tables.json
  python export-tables.py --verify   re-read and check the invariants only
"""
from __future__ import annotations

import hashlib
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IMAGE = HERE / "oracle" / "out" / "maincpu.bin"
OUT = HERE.parent / "rip" / "port"

DIR_TABLE = 0x2552DC          # 16 bytes
FOLD_TABLE = 0x2418B4         # 256 words
SPEED_PTRS = 0x200920         # longs
QUAD_ENTRIES = 65             # 0..90 degrees inclusive
QUAD_STRIDE = QUAD_ENTRIES * 8    # $208
KNOCKBACK = 0x2552EC          # 16 bytes
# The frame-rate GOVERNOR's four PC-relative word tables, read at $23C2B4 /
# $23C2E4 (pairs indexed by $813096) and $23C342 / $23C332 (single words indexed
# by $813094).  See src/framesync.js.
GOV_TABLES = {"t23C3EE": (0x23C3EE, 10), "t23C402": (0x23C402, 10),
              "t23C416": (0x23C416, 5), "t23C420": (0x23C420, 5)}
ANIM_A = 0x25533A
ANIM_B = 0x2553CA
TILT_MIN, TILT_MAX, TILT_STEP = -0x20, 0x20, 4
SCAN_CAP = 512                # see speed_levels(): a scan cap, not the table end

# --------------------------------------------------------------------- WAVE 8
# THE SHOT SUBSYSTEM'S ROM.  Wave 4 exported hand-picked tables as JSON arrays.
# The shot spawn ($249BFC -> $24A222) does not read TABLES, it copies a 38-byte
# RECORD TEMPLATE and then follows three more pointers out of it, so the honest
# export is a set of ROM WINDOWS the port reads the way the 68000 does -- with a
# bounds check that THROWS BY ADDRESS on any read the export did not cover,
# instead of an array index that would silently return undefined.
#
# Each window is here because an instruction reads inside it; the comment names
# the instruction.  Windows are deliberately a little wider than the bytes we
# know are used, because "wider than measured" fails loudly at the export and
# "narrower than used" fails at runtime on the player's machine.
SHOT_WINDOWS = [
    # $249C3E lea $2554EA / $249C88 lea $255502 / $249D5E lea $25551A -- the
    # per-FORMATION pointer tables, and the per-POWER tables they point at
    # ($255532..$2555A9, five longs each at a TWO-byte stride, so the power word
    # must be even -- the same trap as the ship selector).
    (0x2554E0, 0x0100, "$2554EA/$255502/$25551A + the $255532.. power tables"),
    # $249C1A `move.w (A2),D7` with A2 = the LONG at $8127E4 -- a ROM pointer
    # the game stores in RAM at ship select.  MEASURED $25523C, holding 4.  The
    # window is here because the port throws by address if $8127E4 ever points
    # anywhere else, which is exactly what happened the first time it ran.
    (0x255200, 0x0100, "the $8127E4 shot-count words at $25523C.."),
    # $24A222's template: 38 bytes copied field by field into the shot record.
    # $24DA20..$24DB9B is the ten SHOT templates (2 tables x 5 powers).
    (0x24D8A0, 0x0360, "shot templates $24DA20.. + the $24D8AC/$24D918 anim tables"),
    # ...and the LASER templates plus their anim tables.
    (0x24E740, 0x0320, "laser templates $24E8BC.. + $24E744/$24E7D4"),
    # The $25551A family's templates and anim tables ($24DFE8/$24E054 and
    # $24EEA4/$24EF34).  Not reached by the player's own spawn; reached by a
    # SEEDED option-pod shot, whose ($1a,A6) the handlers feed to $241D34.
    (0x24DFE0, 0x0300, "$25551A[0] templates $24E15C.. + $24DFE8/$24E054"),
    (0x24EEA0, 0x0360, "$25551A[1] templates $24F01C.. + $24EEA4/$24EF34"),
    # The OPTION PODS' pointer tables and templates ($24D4E2's $24D2FC/$24D35C).
    (0x24D2E0, 0x00E0, "$24D2FC/$24D35C + their per-power tables"),
    (0x24F400, 0x0C00, "option-pod templates $24F8EC.. and every anim table they point at"),
    (0x251100, 0x0300, "option-pod laser templates $251184.."),
    # $253B72 lea $24DDD6 / $253C7A lea $24DEB2 -- the per-($26,A6) tables the
    # handlers re-point the record's sprite fields from, and their structs.
    (0x24DDD0, 0x01B0, "$24DDD6 and $24DEB2 + the structs they point at"),
    # $253E5A lea $24FC8E
    (0x24FC80, 0x0100, "$24FC8E + its structs"),
    # $253F38 lea $25014C
    (0x250140, 0x0100, "$25014C + its structs"),
    # $241D46 lea ($241AF4,PC) -- the SECOND angle-fold table.  256 words,
    # indexed by the WHOLE angle byte (D3 = D1*2), not by angle&$3f*4 like
    # $2418B4.  Same triangle, different stride: do not alias the two.
    (0x241AF4, 0x0200, "$241AF4 the shot vector's angle-fold table"),
    # $2433C2 lea ($2433D0,PC) -- the 64-longword pseudo-random table.
    (0x2433D0, 0x0100, "$2433D0 the $2433AE pseudo-random longword table"),
    # W31: $2433AE IS ONE OF A FAMILY.  A scan of the whole decrypted image for
    # `addq.b #1,$803917` finds 32 sites in build B, each reading a DIFFERENT
    # canned table off the SAME 8-bit counter.  The stage-1 midboss $26B6FA
    # uses two of them, so their tables are windows now.
    #   $2431F4: `moveq #$3f` masks the index -> 64 bytes, $24324E..$24328D,
    #            and $24328E is the next routine's `addq.b` (far end PINNED).
    (0x24324E, 0x0040, "W31: $2431F4's 64-byte draw table $24324E, indexed by "
                       "$803916 & $3F (the midboss's $26B2AC draws)"),
    #   $242FDE: NO MASK -- `move.w $803916,D0` then `move.b (A0,D0.w),D0` --
    #            so the index is the whole word.  256 bytes, $24301A..$243119,
    #            and $24311A is code (far end PINNED).  In range only because
    #            $23BE36 `clr.w $803916` zeroes the high byte and `addq.b`
    #            never carries into it.
    (0x24301A, 0x0100, "W31: $242FDE's 256-byte draw table $24301A, indexed by "
                       "the WHOLE $803916 word (the midboss's $26B2AC/$26B35E)"),
    # ------------------------------------------------------------- WAVE 12
    # THE SHIP'S OWN SPRITE BLOCK ($24A482) and the OPTION OBJECT ($24C096).
    # One window covers every table both of them index, because they are packed
    # together in $2553xx..$2559xx and splitting them would be a schema decision
    # the ROM does not support.  Named individually so a reader can check any
    # one of them:
    #   $25533A the ship IMAGE pointer table (17 longs per ship, tilt-indexed)
    #   $2553CA the ship's X HALF-EXTENTS -> $2553F2 (NOT animation; see below)
    #   $25545A the ship SHADOW sprite table, read at $249ECE
    #   $255672 the aura's flip/colour words, read at $24A4D0 with ($57,A6)*2
    #   $25567A the aura's 16 sprite longs, read at $24A4BA with ($28,A6)
    #   $2556BA/$255676 their ($1,A6)-bit-7 twins ($24A4F2/$24A510) -- UNREACHED
    #   $2556E2 the glow's per-ship/per-tilt sprite tables ($24A55C)
    #   $255882 ...and their stick-down variant ($24A576) -- UNREACHED
    #   $255A22 the glow's {protection bias, dx, size} struct ($24A562)
    #   $255A36 ...and its variant ($24A57C) -- UNREACHED
    (0x255330, 0x0900, "WAVE 12: $25533A/$2553CA/$25545A/$255672/$25567A/"
                       "$2556BA/$2556E2/$255882/$255A22/$255A36 -- every table "
                       "the ship's draw block $24A482 and its shadow $249EA0 read"),
    # $24C0D2 lea ($24BBAA,PC) / movea.l (A0,D0.w),A0 with D0 = (($5a,A4)-2)*2.
    # MEASURED entries: $24BF6E, $24BFC8, $24C022, each 90 bytes of template.
    # The window runs to $24C07C = $24C022 + 90.
    (0x24BBA0, 0x04E0, "WAVE 12: $24BBAA + the three option TEMPLATES it points "
                       "at ($24BF6E/$24BFC8/$24C022, 90 bytes each)"),
    # ------------------------------------------------------------- WAVE 13
    # THE SCROLL PROGRAM.  `src/background.js` reads all of this the way the
    # 68000 does; every base below is the address of an instruction's operand.
    #
    #   $240D62  the five per-stage TILE BASES, added whole to every map
    #            longword ($240D80 lea ($240D62,PC),A0 / adda.w $813096)
    (0x240D60, 0x0020, "WAVE 13: $240D62 the five per-stage BG tile bases"),
    #   $261252  BG palette block ptrs  ($2611B2)
    #   $261266  BG column-stream ptrs  ($2611D6)
    #   $26153E  the five script PAIRS  ($26152C)
    #   $26157A  stage-1 object stream, 22 entries + $FFFFFFFF ($2620E4)
    #   $261602  stage-1 cue stream, 14 B ($262186)
    #   $261610.. all TEN scripts, 186 records, ending at $261F6E ($262072)
    (0x261240, 0x0D40, "WAVE 13: $261252/$261266/$26153E + the object and cue "
                       "streams + all ten scroll scripts ($261610..$261F6E)"),
    #   $262302  the five BG-element handler tables, and the tables themselves
    #            ($262328 / $26224A..$26227D for stage 1).  Read by op $10 so
    #            the unported-note can NAME the constructor W18 must port.
    (0x262240, 0x0100, "WAVE 13: $26224A..$2622F2 the BG-element handler "
                       "tables and $262302 the per-stage pointer table"),
    #   $225B78  STAGE 1's column stream, 248 columns x 36 B.  Stages 2..5 are
    #            deliberately NOT exported: this wave validated stage 1 and a
    #            read of another stage's stream must be a LOUD THROW BY ADDRESS
    #            rather than a plausible picture.  The next four streams run
    #            $228658/$22A5F8/$22B1E8/$22D770 (recon §2) and are W15's.
    (0x225B78, 0x22E0, "WAVE 13: the STAGE-1 BG column stream, 248 columns "
                       "x 36 B = 8,928 B ($2611D6 -> $26135A)"),
    # ------------------------------------------------------------- WAVE 20
    # THE AIM PAIR.  One window per core, because the two cores' tables are
    # packed contiguously and splitting them by name would be a schema decision
    # the ROM does not support (the same reasoning as the WAVE 12 block above).
    #   $2420C6  8 longs   the octant SIGN dispatch ($24209C jmp) -- each entry
    #                      is $2420AE (sub) or $2420BA (add) and src/aim.js
    #                      CHECKS that rather than trusting an index
    #   $2420E6  8 words   the octant BASE ($242092)
    #   $2420F6  129 bytes THE ARCTAN LUT ($242088).  NOT formula-reconstructible:
    #                      it deviates from a true arctan by +1.65 units of 512
    #                      at index 10 (20-recon-aiming §2), in the near-axis
    #                      band, which is where most shots live.  Ship the bytes.
    (0x2420C0, 0x0100, "WAVE 20: aim64's three tables -- $2420C6 octant signs, "
                       "$2420E6 octant bases, $2420F6 the 129-byte arctan LUT"),
    #   $242312  8 x 8 B   the octant stubs ($24230A jsr (A0,D4.w)), each
    #                      <add|sub>.w D0,D1 / andi.w #$FF,D1 / rts
    #   $242352  8 words   the octant BASE ($2422F6)
    #   $242362  65 bytes  the aim256 LUT ($2422EC)
    (0x242300, 0x0100, "WAVE 20: aim256's tables -- $242312 octant stubs, "
                       "$242352 bases, $242362 the 65-byte LUT"),
    # THE ENEMY TYPE TABLE.  256 entries x 8 bytes in TWO halves, split at type
    # $80 -- `census.py entry()`, and the split is why one window will not do.
    # Every entry is (init, handler) and EVERY init is an 8-byte stub whose body
    # is at init+8 (20-recon-enemy-census: 256 of 256, verified mechanically).
    (0x267820, 0x0410, "WAVE 20: the enemy type table, types $00..$7F "
                       "($267824, 8 bytes per type: init, handler)"),
    (0x27E410, 0x0410, "WAVE 20: the enemy type table, types $80..$FF ($27E412)"),
    # THE TWO TURRET TYPES' PROTOTYPES.  $2637A2 copies the SUB-record prototype
    # ($20 bytes per sub-record) and $26377A copies D0+1 words into ($16,A5).
    # Only the two types this wave validates are exported: a read of any other
    # type's prototype must be a LOUD THROW BY ADDRESS, not a plausible enemy.
    (0x268180, 0x0080, "WAVE 20: type $10's record prototype $268192 (16 words, "
                       "$2680E0 moveq #$F) and sub-record prototype $2681B2"),
    (0x268800, 0x0060, "WAVE 20: type $11's record prototype $268808 (16 words, "
                       "$26872E moveq #$F) and sub-record prototype $268828"),
    # THE 32-DIRECTION TURRET SPRITE TABLES, read at $2683B6 / $268A4E with the
    # facing rounded by `addq.b #1,D1 / andi.w #$3E,D1 / add.w D1,D1`.  The
    # windows also carry the 16-entry MUZZLE table $268B1E ($268AEC) and the
    # 16-direction body tables $268594 / $268B9E ($26831E / $2689B6).
    (0x268580, 0x01A0, "WAVE 20: type $10's $268594 (16 dir body) and $268694 "
                       "(32 dir turret) sprite tables"),
    (0x268B10, 0x0220, "WAVE 20: type $11's $268B1E muzzle table, $268B9E body "
                       "table and $268C9E 32-direction turret sprite table"),
    # ------------------------------------------------------------- WAVE 21
    # THE ENEMY BULLET PATTERN GENERATORS.  src/bullets.js and
    # src/bulletmath.js read every one of these the way the 68000 does.
    #
    #   $281956  39 longs   the TEMPLATE pointer table ($281564 movea.l (A1,D0.w))
    #   $2819F4  39 x $14   the templates themselves, ending at $281CD6 where
    #                       code begins ($4A79 tst.w abs.l).  The extent is
    #                       pinned from BOTH ends: entry[39] of the pointer
    #                       table is $018100, not a pointer.
    (0x281950, 0x0390, "WAVE 21: $281956 the 39 bullet-KIND template pointers "
                       "and the 39 x 20-byte templates at $2819F4..$281CD5"),
    #   $2815C6  39 longs   the SPAWN-INIT pointer table ($2815B6 adda.w D0,A1)
    (0x2815C0, 0x00B0, "WAVE 21: $2815C6 the 39 spawn-init pointers "
                       "(nine distinct routines)"),
    #   $282030  39 longs   the BEHAVIOUR pointer table ($281F16 adda.w D0,A0).
    #                       The BODIES are not ported by wave 21; the table is
    #                       exported so `behaviourFor` can name the address it
    #                       is not running.
    (0x282030, 0x00A0, "WAVE 21: $282030 the 39 behaviour-initialiser pointers"),
    #   $283F50  256 words  THE FOLD TABLE ($2841A2 lea ($283F50,PC),A2 /
    #                       adda.w (A2),A3).  MEASURED to be exactly
    #                       8*triangle(i), period 128, peak 64 -- so 256
    #                       directions fold onto 65 quarter-angle records.
    (0x283F50, 0x0200, "WAVE 21: $283F50 the 256-word direction FOLD table"),
    #   $283D4C  32 entries x 12 B  the MUZZLE-OFFSET + sprite table the shared
    #                       behaviour helper $2820CC indexes by
    #                       ((dir+4)&$F8)*3/2 (kinds 0/1/7/8/12/13/...). Each
    #                       entry is {posOffset long, descriptor long, attr word};
    #                       the posOffset's two signed halves (each >>1) are added
    #                       to posA/posB at spawn. 32 dir-buckets x 12 = 384 B;
    #                       the byte at $283ECC is `add.w D0,D0` (next routine).
    (0x283D4C, 0x0180, "WAVE 26: $283D4C the 32-entry direction muzzle-offset "
                      "table read by $2820CC (bullet behaviour spawn helper)"),
    #   $283C4C  32 words  the direction-sprite OFFSET table the shared epilogue
    #                       $283C0E indexes by ((dir+4)>>2)&$3E (kinds 7/...).
    #                       Sprite-only (selects a renderOffs frame); 64 B.
    (0x283C4C, 0x0040, "WAVE 26: $283C4C the 32-word direction-sprite offset "
                      "table read by the $283C0E behaviour epilogue"),
    #   $2822EC  32 words  the direction-sprite OFFSET table the OTHER shared
    #                       epilogue, $2822AE, indexes by (dir+4)&$F8. Note this
    #                       is a DIFFERENT table from $283C4C above and a
    #                       different index expression -- $2822AE masks to $F8
    #                       where $283C0E shifts >>2 and masks $3E. 64 B.
    #
    #   W26 transcribed $2822AE but NO KIND DISPATCHED TO IT, so this window was
    #   never needed and never noticed to be missing. W27's kinds 2 and 21 are
    #   the first to reach it, and the port threw immediately and by address --
    #   `UNPORTED $2822FC: word outside every ROM window`. That throw is the
    #   system working: the alternative to a missing window is invented data.
    #
    #   SIZE CORRECTION (W27, same day): this window was first added as $40
    #   bytes, on the assumption "32 words = 64 bytes". WRONG. $2822AE indexes
    #   it as `move.w ($2822EC,A1,D0),D1` with D0 = (dir+4)&$F8, so D0 is a BYTE
    #   OFFSET running 0, 8, 16 ... $F8 -- the 32 entries are spaced 8 bytes
    #   apart, not packed. The last one lives at $2822EC+$F8, so the table needs
    #   $FA bytes, and it ends exactly where kind 3's body begins ($2823EC), so
    #   $100 is the true extent.
    #
    #   It passed anyway, because every test written against this table used
    #   `dir: 0x10` -> D0 = $10 -> well inside $40. The first test to use
    #   dir $40 threw `UNPORTED $28232C` on its first frame. A window validated
    #   only by inputs that all happen to be small is not validated.
    (0x2822EC, 0x0100, "WAVE 27: $2822EC the 32-entry direction-sprite offset "
                      "table read by the $2822AE behaviour epilogue; indexed by "
                      "(dir+4)&$F8 as a BYTE offset, so it spans $100 to $2823EC"),
    #   $2821FA  kind 2's sprite-frame table: 9 pointers into $28221E..$2822AC,
    #                       each of which is a list of $1BFxxx frame descriptors.
    #                       $2822AE resolves *(A0 + $2822EC[d0]) then
    #                       *(that + index). Covers both indirections: $2821FA
    #                       through the end of the pointer lists at $2822AC.
    (0x2821FA, 0x00B4, "WAVE 27: $2821FA kind 2's dir-indexed sprite-frame "
                      "pointer table + the frame lists it points into"),
    #   $282C8E  kind 21's equivalent of $2821FA. Same shape, same two-level
    #                       indirection, different frames.
    (0x282C8E, 0x00B4, "WAVE 27: $282C8E kind 21's dir-indexed sprite-frame "
                      "pointer table + the frame lists it points into"),
    #   $283704  kind 33's 6-entry descriptor ring, read by $2836E2 as
    #                       `lea $283704(pc),A0 / adda.w D0,A0 / move.l (A0),$a`
    #                       with D0 = the WORD at record +$2C.
    #
    #   SIZED FROM THE INDEX EXPRESSION, not the entry count. The initialiser
    #   seeds +$2C = $14 and the continuation does `subq.w #$4 / bcc /
    #   move.w #$C`, so the reachable indices are $14, $10, $C, $8, $4, $0 --
    #   the highest is $14 and the read is a LONGWORD, so the extent is $18.
    #   $283704 + $18 = $28371C, exactly where kind 34's body begins: an
    #   abutting bound, the same evidence used for $2822EC's $100.
    #   $2830EA  kind 26's 9-entry dir-indexed sprite-frame table, reached
    #                       through the $283C8C epilogue (`lea $2830EA(pc),A0`
    #                       then `adda.w $283C4C[d1],A0 / move.l (A0),$a`).
    #
    #   REQUIRED, not sprite-only: $283C46 also writes +$10 = frame + (+$14),
    #   and kind 26's CONTINUATION uses +$10 as its ring limit.  Without the
    #   window the ring bound is unavailable, not merely the picture.
    #
    #   Sized from the index expression: the $283C4C offsets top out at $20
    #   (measured, not assumed -- the 32 words are 0,4,8...$20 and back down),
    #   the read is a longword, so the extent is $24.  $2830EA + $24 = $28310E,
    #   exactly where kind 26's continuation begins: an abutting bound.
    (0x2830EA, 0x0024, "WAVE 27: $2830EA kind 26's 9-entry dir-indexed sprite-"
                      "frame table, read by the $283C8C epilogue; also supplies "
                      "the +$10 ring limit its continuation compares against"),
    (0x283704, 0x0018, "WAVE 27: $283704 kind 33's 6-entry descriptor table, "
                      "indexed by the word at record +$2C ($14 down to 0, then "
                      "wrapping to $C -- a 2-entry lead-in over a 4-entry ring)"),
    #   $282714  kind 7's 9-entry dir-indexed sprite-frame table, read by the
    #                       $283C0E epilogue (`lea $282714(pc),A0 / bra $283C0E`
    #                       then `adda.w $283C4C[d1],A0 / move.l (A0),$a`).
    #
    #   WAVE 52 ADDED THIS WINDOW AND IT IS A CONSEQUENCE, NOT AN OVERSIGHT.
    #   `src/mover.js` ran the $283C0E epilogue only `if (ctx.sprites)` -- and
    #   until W52 nothing ever passed a sprite sink, so the read never happened
    #   and the missing window could not be reached.  Wiring the enemy bullets'
    #   emit reached it on the first run: `UNPORTED $282718` at step 1,417.
    #
    #   Sized exactly like $2830EA above and for the same reason: the $283C4C
    #   offsets top out at $20 (the 32 words are 0,4,8..$20 and back down) and
    #   the read is a longword, so the extent is $24.  $282714 + $24 = $282738,
    #   which is kind 7's own CONTINUATION -- an abutting bound, the same
    #   evidence $2830EA and $2822EC are sized by.
    (0x282714, 0x0024, "WAVE 52: $282714 kind 7's 9-entry dir-indexed sprite-"
                      "frame table, read by the $283C0E epilogue. Reachable "
                      "only once a sprite sink exists (W52)"),
]

# WAVE 21 -- THE VELOCITY FIELD, exported in full and here is why.
#
# `$284190` indexes `$200920` with a BYTE from record +$1A, so the domain is
# 0..255 and nothing narrows it: the speed a bullet gets is
# `template base (20) + the call site's bias + $813160 + $812950`, and the last
# two are LIVE VARIABLES ($252C8E writes $812950 every single frame).  A derived
# subset -- the trick `speed_index_set()` plays for the player's own shots -- is
# a guess here, and a guess that fails on a player's machine rather than at
# export time.  The table's extent is proven from both ends: the pointer table
# is an exact arithmetic progression for exactly 256 entries (entry 256 and its
# two neighbours are 0), and the last quadrant table ends at $221520, the next
# known data object.  So: one window, $200920..$22151F, 134,144 bytes.
VELOCITY_FIELD = (0x200920, 0x221520 - 0x200920,
                  "WAVE 21: the WHOLE velocity field -- $200920's 256 longword "
                  "pointers and the 256 x 65 x 8-byte quadrant tables they "
                  "point at, $200D20..$22151F")
SHOT_WINDOWS.append(VELOCITY_FIELD)

# WAVE 22 -- THE SPAWN SIDE.  src/spawn.js reads the stage table, the stage-1
# spawn script and the aux table the way the walker `$2633BE` does.  The two
# enemy TYPE tables (LO `$267824` / HI `$27E412`, 8 bytes per type -- init then
# handler) are already exported by wave 20 and are reused unchanged.
#
#   $263336  5 stages x 16 bytes  the STAGE TABLE `$263386` installs from: each
#           entry is (script_ptr, aux_ptr, res_ptr, pad).  `$813096` (stage*4)
#           x4 is the index; stage 1 -> (script $230C6C, aux $23170C, res $231852).
#   $230C6C  339 records x 8 B + $FFFF terminator = 2714 B, the stage-1 SPAWN
#            SCRIPT.  The walker matches each record's first word (the trigger)
#            against $8130CE.  The 8-byte layout is [trig:W][param:W][type:B]
#            [flags:B][idx:W&$FFF] (census.py script_records).  Stages 2..5 are
#            deliberately NOT exported: a read of another stage's script must be
#            a LOUD THROW BY ADDRESS, not a plausible walk (the same rule W13
#            applied to the BG column stream).
#   $23170C  the stage-1 AUX table, word offsets into resource #$1F (the
#            movement-script bytes), indexed by each record's 12-bit data idx.
#            Stage 1's max idx is 162, so the live prefix is 326 B; the window
#            carries an honest margin.  The resource #$1F data itself is W24's
#            (the movement interpreter $2638A6); the port resolves the pointer
#            and notes the body unported.
SHOT_WINDOWS.extend([
    (0x263330, 0x0060, "WAVE 22: $263336 the five-stage spawn table (16 B per "
                       "entry: script ptr, aux ptr, resource ptr, pad)"),
    (0x230C6C, 0x0AA0, "WAVE 22: the STAGE-1 spawn script, 339 records x 8 B + "
                       "$FFFF terminator ($230C6C..$231706)"),
    (0x23170C, 0x0150, "WAVE 22: the STAGE-1 aux table -- per-record word "
                       "offsets into resource #$1F ($23170C, max idx 162)"),
    # WAVE 24 -- resource #$1F, the movement byte-code streams.  $2633A2 installs
    # the base into protection slot #$1F and $26341E `adda.w aux[idx],A1` resolves
    # each stream pointer = $231852 + aux[idx].  163 streams, 3454 B total
    # ($231852..$2325D0, measured by w24streams.py).  Stages 2..5 are deliberately
    # NOT exported: a read of another stage's stream stays a LOUD THROW BY ADDRESS.
    (0x231852, 0x0D7E, "WAVE 24: STAGE-1 resource #$1F -- the 163 movement "
                       "byte-code streams ($231852..$2325D0, 3454 B)"),
])

# WAVE 23 -- ENEMY STATS BECOME DATA.  The two prototype loaders `$2637A2`/
# `$26377A` (ported by W20 in src/enemyproto.js) copy every stage-1 type's
# hitbox/HP/speed/heading/palette/animation/draw-bucket out of ROM tables at
# spawn.  W20 exported only the two turret types' prototypes; this wave exports
# the remaining 19 stage-1 type prototype pairs plus the shared sprite/bucket/
# palette tables the init+8 bodies index.  (Types $10/$11 reuse W20's windows.)
#
# Each window is sized from the prototype addresses census2.py resolved and the
# loader arithmetic: sub-record prototype = 28 * (runLen+1) bytes for the long
# form (every stage-1 type's flags word has bit 15 set); record prototype =
# (D0+1)*2 bytes (the moveq/move.w #N,D0 before `jsr $26377A`).  The small
# palette tables (indexed by $813094, the loop word) sit immediately before the
# record prototype and are carried in the same window.  A read of any field the
# port has not covered stays a LOUD THROW BY ADDRESS -- the export widens, the
# port never returns undefined.
ENEMY_PROTO_WINDOWS = [
    # the two damage-first protos that are NOT shared (the family's shared
    # sprite tables $269E48/$269EC8 and bucket table $267F70 follow).
    (0x2697B0, 0x0050, "W23: type $31 protos + palette tables $2697B0/$2697BA "
                       "(sub $2697DA, rec $2697CE)"),
    (0x269CB0, 0x0040, "W23: type $05 protos (sub $269CCE, rec $269CB4)"),
    (0x26A2B0, 0x0040, "W23: types $07/$27 protos (sub $26A2C6, rec $26A2B0)"),
    (0x26A5B0, 0x0040, "W23: type $08 protos (sub $26A5C8, rec $26A5B2)"),
    (0x26A820, 0x0040, "W23: type $09 protos (sub $26A844, rec $26A82E)"),
    (0x26ACF0, 0x0040, "W23: type $0B protos (sub $26AD0C, rec $26ACF6)"),
    # the midboss $0D: runLen 16 -> 17 sub-records x 28 B = 476 B from $26B50E.
    (0x26B4F0, 0x0220, "W23: type $0D (THE MIDBOSS) protos -- 17 sub-records "
                       "(sub $26B50E, rec $26B4FA)"),
    # W31: THE MIDBOSS HANDLER'S OWN TABLES.  Extents pinned from BOTH ends.
    #   $26B214  the DEATH-BURST list walked by $26B1D2: 14 records of
    #            (word D1, word D0, long -> +$26), terminated by $FFFF at
    #            $26B284, and $26B286 is the next routine's first instruction.
    (0x26B210, 0x0080, "W31: the midboss's death-burst list $26B214 -- 14 "
                       "records of 8 B, $FFFF-terminated, walked at $26B1D2"),
    #   $26BE70  8 longs, read at $26BE40 with ($A,A0) which steps 4 and stops
    #            at $1C; abuts $26BE90.
    #   $26BE90  32 longs, read at $26BE1C with ($30,A0) masked $7F; $26BF10
    #            is `lea $26BF42(pc),A0`, i.e. code.
    #   $26BF42  32 longs, read at $26BF10 with ($8,A6) which steps 4 to $7C;
    #            $26BFC2 is `lea $26BFE8(pc),A0`, i.e. code.
    #   $26BFE8  5 longs, read at $26BFC2 with ($24,A5) which steps 4 and wraps
    #            at $14; the five are spaced $EA4 and $26BFFC breaks the run.
    # One window covers all four plus the two tail routines interleaved with
    # them ($26BF10 and $26BFC2), which is how the ROM lays them out.
    (0x26BE70, 0x0190, "W31: the midboss's four sprite tables $26BE70 (8), "
                       "$26BE90 (32), $26BF42 (32) and $26BFE8 (5 longs)"),
    # the scripted carriers $20/$21 (sub only, $272A90) and prop $24.
    (0x272A90, 0x0020, "W23: types $20/$21 sub-record prototype $272A90"),
    (0x296FF0, 0x0020, "W23: type $24 sub-record prototype $296FF2"),
    # the multi-sub-record types (runLen 1 -> 2 sub-records x 28 = 56 B).
    (0x273920, 0x0080, "W23: type $80 protos + palette $273922 (sub $27394E, "
                       "rec $27392C)"),
    (0x274740, 0x0070, "W23: type $82 protos + palette $27474A (sub $274770, "
                       "rec $274754)"),
    (0x275890, 0x0070, "W23: type $85 protos + palette $275890 (sub $2758B0, "
                       "rec $27589A)"),
    (0x275EA0, 0x0080, "W23: type $88 protos + palette $275EA2 (sub $275ECC, "
                       "rec $275EAC)"),
    (0x2766E0, 0x0030, "W23: type $8A protos (sub $2766E6, rec $2766E0)"),
    (0x276850, 0x0030, "W23: type $8B protos (sub $276862, rec $27685E)"),
    (0x277300, 0x0040, "W23: type $89 protos + palette $27730C (sub $277322, "
                       "rec $277316)"),
    # the boss $0E: runLen 8 -> 9 sub-records x 28 = 252 B from $292806.
    (0x2927F0, 0x0140, "W23: type $0E (THE BOSS) protos -- 9 sub-records "
                       "(sub $292806, rec $2927F6)"),
]
# the shared tables the init bodies index by heading / loop / spawn param.
# $267F70: bucket-emitter pair table indexed by (sub +$1F)<<3 -- 2 longs each.
# $269E48/$269EC8: the damage-first family's 32-direction sprite + bucket
#   tables, indexed by ((heading)&$3E)<<1 (a longword at every 4-byte stride).
# $268694/$268C9E: type $10/$11's 32-direction sprite tables (same heading
#   arithmetic, reached after addq #1 -- still 0x80 bytes).
# $272D7A/$272DFA/$272E7A/$272F7A: the aim-derived sprite/bucket tables for
#   types $80/$82/$85/$88/$89 (16 longs, indexed by the aim direction).
# $2763D8: type $88's sub-record sprite table, indexed by (sub +$28) word.
ENEMY_STAT_TABLES = [
    (0x267F60, 0x00A0, "W23: the bucket-emitter table $267F70 (types $10/$11, "
                       "indexed by (sub +$1F)<<3)"),
    (0x268690, 0x0090, "W23: type $10's 32-direction sprite table $268694"),
    (0x268C90, 0x0090, "W23: type $11's 32-direction sprite table $268C9E"),
    (0x269E40, 0x0110, "W23: the damage-first family's shared sprite table "
                       "$269E48 + bucket table $269EC8 (16-dir, heading-indexed)"),
    (0x272D70, 0x0190, "W23: the aim-derived sprite/bucket tables $272D7A "
                       "($88) and $272DFA ($82/$85), 16 longs each"),
    (0x272E70, 0x0090, "W23: the aim-derived sprite table $272E7A ($89)"),
    # W30: THE SPRITE-EMITTER STUB FAMILY, read as DATA by src/spritequeue.js's
    # `resolveEmitStub`.  The enemy handlers reach an enqueue through a POINTER
    # ($267F70's twelve longwords, $27829C's twenty-four), and the bucket a
    # pointer feeds is the `lea <abs>.l,A0 / adda.w <abs>.l,A0` pair inside the
    # stub itself.  Resolving it FROM THE CARTRIDGE is what stops the port
    # carrying a transcribed pointer->bucket map that agrees with itself.
    # $23D760 is the `rts` before $23D762; $23DF98 is inside $23DF86's body and
    # the window ends past the last stub's counter operand.
    # W31 WIDENED THIS from $840 to $910.  The midboss `jsr $23E056` twice
    # ($26BE3A/$26BE60) -- a FOURTH stub shape (`move.l A0,-(A7) / move.l
    # D0,-(A7)` in front of the same fourteen instructions), and it sat
    # $B6 bytes past the old end, so `resolveEmitStub` could not read it.
    (0x23D760, 0x0910, "W30/W31: the sprite-emitter stub family "
                       "$23D762..$23E08C, read as data to resolve "
                       "(bucket, convention) per stub"),
    # W30: the 24-entry emitter dispatch $27829C (type $8A's $2767C2) and its
    # neighbour $278320, and the $267F70 pair table is already covered by the
    # W23 $267F60 window.
    (0x278290, 0x00B0, "W30: $27829C the 24-entry sprite-emitter dispatch "
                       "(type $8A $2767C2) + $278320's death-effect words"),
    # W30: $267FC6's FOUR position-box tables, five longwords each, contiguous
    # at $242562..$2425B1 -- pinned from BOTH ends ($242560 is the previous
    # routine's `rts`, $2425B2 is `48E7 C080 movem.l`, i.e. code).
    (0x242560, 0x0054, "W30: $267FC6's position-box tables $242562/$242576/"
                       "$24258A/$24259E, 5 longs each, indexed by $813096"),
    # W30: type $85/$86's handler $275914 fires at $275AD0 with D3 taken from
    # a 32-entry LONGWORD muzzle table at $27327A ($275AAA lea $27327A,A4 /
    # $275ABC move.l (A4,D0.w),D3 with D0 = (($28,A5) & $3E) * 2, so byte
    # offsets 0..$7C).  EXTENT PINNED FROM THE DATA, not from the index alone:
    # entries 0..31 are a clean circle ($0500,$0000 / $0040,$03C0 / $FB80,$0000
    # / $0040,$FC40 at 0/8/16/24) and entry 32 at $2732FA breaks it, so the
    # table is $27327A..$2732F9 and the window covers exactly that.
    (0x273270, 0x0090, "W30: type $85/$86's 32-entry muzzle-vector table "
                       "$27327A, read at $275ABC by the $2813F0 fire"),
    (0x272F70, 0x0090, "W23: the aim-derived sprite/bucket table $272F7A ($80)"),
    # W30: type $80's handler $2739C0 reads three more longword tables.
    # $2735FA and $2736FA are indexed by `((D1+2) & $FC)` -- byte offsets
    # 0..$FC, so 64 longwords = $100 bytes each, and the pair is pinned from
    # both ends: $2735FA + $100 == $2736FA and $2736FA + $100 == $2737FA, which
    # is type $80's own init stub (code).
    (0x2735F0, 0x0220, "W30: type $80's two fan-direction tables $2735FA "
                       "($2817B8 loop) and $2736FA ($2817A8 loop), 64 longs each"),
    # $27347A is indexed by `(D1 & $3E) * 2` -> 0..$7C, 32 longwords.  EXTENT
    # PINNED FROM THE DATA: entries 0..31 are a clean circle ($0600,$0000 /
    # $0040,$0540 / $FA80,$0000 / $0040,$FAC0) and entry 32 at $2734FA breaks it.
    (0x273470, 0x0090, "W30: type $80's 32-entry muzzle table $27347A, read at "
                       "$273D50/$273D78 by the two $281484 fires"),
    (0x2763D0, 0x0050, "W23: type $88's sub-record sprite table $2763D8 "
                       "(indexed by (sub +$28))"),
    # ===================== W36: the seven remaining stage-1 handlers ========
    # $269BB6: the damage-first family's FOUR-entry animation table, read at
    # $269B64 `move.l ($269BB6,PC,D2.w),D2` with D2 = ($20,A5), a byte offset
    # the same block cycles 0/4/8/$C (`addq.w #$4` + `andi.w #$F`).  PINNED
    # FROM BOTH ENDS: $269BB4 is the `nop` after `$269BAE jmp $23DF58`, and
    # $269BC6 is type $05's init stub (`3B7C 0000 0004 / 4E75`), i.e. code.
    (0x269BB6, 0x0010, "W36: the damage-first family's 4-entry draw table "
                       "$269BB6 ($269B64, ($20,A5) cycling 0/4/8/$C)"),
    # $269F48: the family's 32-entry longword MUZZLE table, read at $269DEC
    # ($05), $26A762 ($08), $26A922 ($09), $26ADEC and $26AEB0 ($0B) with the
    # index `((D2 + 1) & $3E) * 2`, i.e. byte offsets 0..$7C.  PINNED FROM BOTH
    # ENDS: entries 0..31 are a clean circle ($0380,$0000 / $0340,$00C0 /
    # $FC00,$0000 / $0340,$FF40 at 0/1/16/31) and $269FC8 is `3B7C 0000 0004 /
    # 4E75` -- the next type's init stub, code.
    (0x269F48, 0x0080, "W36: the damage-first family's 32-entry muzzle table "
                       "$269F48, read by the $2814AC fires"),
    # $26990E: type $31's ANIMATION table, 8-byte entries of which the handler
    # reads six (`move.l (A0)+,($A,A6)` then `move.w (A0)+,($18,A5)`), stepped
    # by `addq.w #$8,($1A,A5)`.  PINNED FROM BOTH ENDS BY THE HANDLER ITSELF:
    # $2698B2 frees the record when the cursor reaches $230, and
    # $26990E + $230 == $269B3E, which is the damage-first family's shared draw
    # block -- instructions.  So the table is exactly 70 entries.
    (0x26990E, 0x0230, "W36: type $31's 70-entry animation table $26990E "
                       "(cursor ($1A,A5), wrap $230 == $269B3E, code)"),
    # $2731FA: type $88's 32-entry longword fan-direction table, read at
    # $2761AC/$276200 with `(D1 & $3E) * 2` -> 0..$7C.  PINNED FROM BOTH ENDS:
    # entries 0..31 are a clean circle ($0400,$0000 / $FD00,$0000 at 0/16) and
    # $2731FA + $80 == $27327A, which is type $85's muzzle table -- the table
    # W30 already windows separately, so the two abut exactly.
    (0x2731FA, 0x0080, "W36: type $88's 32-entry fan-direction table $2731FA "
                       "($27619A lea, read by both turrets)"),
    # $2732FA: type $89's fan table, and its entries are PAIRS.  $27744C and
    # $27744E double the masked heading TWICE, so the stride is 8 bytes, and
    # $277452/$277462 read `(A4)+` twice -- byte offsets 0..$F8 plus 8.  The
    # extent is INDEX-DERIVED ($100 bytes, 32 headings x 2 longwords) and NOT
    # pinned by code at the far end: $2733FA is more vector data.  What pins it
    # is the grid the neighbours sit on -- $2731FA+$80 = $27327A, +$80 =
    # $2732FA, +$100 = $2733FA -- and that is stated rather than dressed up.
    (0x2732FA, 0x0100, "W36: type $89's 32-heading PAIRED fan table $2732FA "
                       "($27743C lea, two move.l (A4)+ per fire)"),
    # $2970D8: type $24's 16-entry longword sprite table, read at $2970BA
    # `adda.w ($18,A5),A0` with ($18,A5) masked `andi.w #$3F` -> 0..$3C.
    # PINNED FROM BOTH ENDS: $2970D4 is the last instruction of the handler and
    # $297118 is `3B7C 000B 0004 / 4E75`, the next init stub -- code.
    (0x2970D8, 0x0040, "W36: type $24's 16-entry sprite table $2970D8 "
                       "(cursor ($18,A5) & $3F)"),
    # $23F896: A FIFTH SPRITE-EMITTER STUB SHAPE, read as data by
    # `resolveEmitStub` exactly as the $23D762 family is.  It sits $1826 bytes
    # past the end of W30/W31's $23D760 window, so it needs its own, and it
    # opens `41F9 <buf> D0F9 <ctr>` like the others but puts the counter bump
    # BEFORE `lea $2(A6),A1` instead of after the writes.  The window covers
    # the whole routine $23F896..$23F8D0 (`rts`).
    (0x23F890, 0x0050, "W36: the sprite-emitter stub $23F896 (bucket 21, "
                       "type $31's three enqueues), read as data"),
    # $2687FE: type $11's loop-indexed palette table (read with `lea $2687FE;
    # adda $813094`), sitting just BELOW W20's $268800 rec-proto window.
    (0x2687F0, 0x0020, "W23: type $11's palette table $2687FE (indexed by "
                       "$813094, the loop word)"),
    # $242E42: the rank-adjustment BYTE table read by $242E24 (`move.b (A0,D0.w)`
    # with D0 = $803916 & $7F, so 128 entries). $242E24's return is halved and
    # added to type $11's bucket word (+$28) at $26874C -- a done-when field.
    (0x242E42, 0x0080, "W23: the $242E24 rank-adjustment byte table $242E42 "
                       "(indexed by $803916 & $7F, read in type $11's init)"),
]
SHOT_WINDOWS.extend(ENEMY_PROTO_WINDOWS)
SHOT_WINDOWS.extend(ENEMY_STAT_TABLES)

# The init STUBS: each stage-1 type's init-body entry is init+8, and the
# 8-byte stub at init (`move.w #N,($4,A5) / rts`) holds the run-length at
# init+2 that `initDispatch` reads (`rom.u16(init + 2)`).  These are CODE bytes
# the port reads as data, one 0x10-byte window per stub.  (Types $10/$11 reuse
# these windows; their protos are in the W20 windows above.)
ENEMY_INIT_STUBS = [
    (0x2680A0, 0x0020, "W23: type $10 init stub $2680B0 (run-length @ init+2)"),
    (0x268710, 0x0020, "W23: type $11 init stub $268714 (run-length @ init+2)"),
    (0x269740, 0x0020, "W23: type $31 init stub $26974C"),
    (0x269BC0, 0x0020, "W23: type $05 init stub $269BC6"),
    (0x26A1E0, 0x0010, "W23: types $07/$27 init stub $26A1E2"),
    (0x26A4B0, 0x0020, "W23: type $08 init stub $26A4B4"),
    (0x26A780, 0x0020, "W23: type $09 init stub $26A78C"),
    (0x26AB90, 0x0020, "W23: type $0B init stub $26AB98"),
    (0x26B470, 0x0020, "W23: type $0D init stub $26B47C"),
    (0x272A40, 0x0010, "W23: types $20/$21 init stub $272A42"),
    (0x2737F0, 0x0020, "W23: type $80 init stub $2737FA"),
    (0x274620, 0x0020, "W23: type $82 init stub $274622"),
    (0x275810, 0x0020, "W23: type $85 init stub $275812"),
    (0x275D90, 0x0020, "W23: type $88 init stub $275D98"),
    (0x2766A0, 0x0020, "W23: type $8A init stub $2766A6"),
    (0x276810, 0x0020, "W23: type $8B init stub $27681C"),
    (0x277270, 0x0010, "W23: type $89 init stub $277270"),
    (0x2926D0, 0x0020, "W23: type $0E init stub $2926DA"),
    (0x296FA0, 0x0020, "W23: type $24 init stub $296FA8"),
]
SHOT_WINDOWS.extend(ENEMY_INIT_STUBS)

# WAVE 34 -- THE LEDGER'S TWO SMALL TABLES, and the extent is deliberately tight.
#
#   $287DF0  the CHAIN-METER CAP, read at `$28616C move.w (A0,D2.w),$81B5B2`
#            with D2 = `$813098 * 2` (the LOOP word, doubled at $286164).  The
#            bytes are `0038 005A` -- 56 and 90 -- and W19 MEASURED 56 on the
#            board for loop 1.  `$813098` is 0 or 1, so two entries is the whole
#            index space.
#   $287DF4  the PER-HIT METER REFILL, read at `$2862D4` (P1) and `$286484`
#            (P2) with the weapon selector `$81043E`/`$8104A0` UNSCALED -- it is
#            already a byte offset.  The bytes are `0014 0012` = 20 and 18.
#
# ONE 8-BYTE WINDOW, NOT MORE.  `$287DF8` onward reads `0118 2223 0084 6001 ...`
# which are not plausible refill amounts, and every RAM dump this project holds
# has `$81043E` = 0, so a third entry would be a guess about a table nobody has
# indexed.  A read past the end is a LOUD NAMED THROW out of `src/rom.js`, which
# is the correct answer to an unproven extent -- and is how W31 found that speed
# level $70 was missing rather than silently reading a zero.
SHOT_WINDOWS.append(
    (0x287DF0, 0x0008, "W34: the chain-meter CAP table $287DF0 (by $813098*2, "
                       "read at $28616C) and the per-hit REFILL table $287DF4 "
                       "(by $81043E/$8104A0, read at $2862D4/$286484)"))

# ---------------------------------------------------------------- WAVE 45
# THE BEAM.  `37-recon-laser.md` §2.3 measured that wave 8's 107 windows cover
# the BOMB-LASER's templates and NOTHING of the beam's, and §9.1 asks for these
# first because every routine in the subsystem reads through them.  Widths are
# generous on purpose -- `export-tables.py`'s own rule is "wider than measured
# fails at the export, narrower than used fails on the player's machine".
#
# ONE WINDOW FOR THE WHOLE $24A8xx..$24B8xx BLOCK, and the reason is the same
# one the WAVE 12 block gives: the five template FAMILIES, the per-type SCRIPTS
# they point at, the per-family ANIM TABLES those point at and the two
# sub-templates `$254C1E` copies are packed contiguously and interleaved, and
# naming each by extent would be a schema decision the ROM does not support.
# MEASURED contents, in address order:
#   $24A824  the hitbox/size word table ($254CB0, indexed by power/formation/ship)
#   $24A86A  the type-2/7/12/17 SCRIPTS ($24A86A/$24A89C/$24A8CE/$24A900)
#   $24A932  family 1, 25 x $26 -- what $24CAAE seeds into pool slot 28
#   $24ACE8  family 2's sixteen anim tables, $28 bytes each
#   $24AF68  family 2, 20 x $0E -- $24CB3A's per-frame segment
#   $24B048  family 3's scripts
#   $24B0A0  families 3, 4 and 5 -- $24CCD0's beam HEAD, 10 + 10 + 5 x $20
#   $24B420  the `($28,A6)` sub-template $254C1E copies into $811892
#   $24B6D2  the `($2c,A6)` sub-template $254C1E copies into $811EF2
SHOT_WINDOWS.extend([
    (0x24A800, 0x1100, "W45 THE BEAM: $24A824 the hitbox table, the type "
                       "scripts, all five template families ($24A932 x25x$26, "
                       "$24AF68 x20x$0E, $24B0A0/$24B1E0/$24B320 x$20) and "
                       "every anim table and sub-template they point at"),
    (0x24BB00, 0x00A0, "W45 THE BEAM: $24BB0A, the (offset, pointer) pairs "
                       "$254FE6 puts in $811F32 and $255042 walks"),
    (0x24CFB0, 0x0180, "W45 THE BEAM: the five pointer tables $24CFBA (25), "
                       "$24CFE2 (10), $24D00A (5), $24D01E/$24D026/$24D03A, "
                       "$24D076/$24D07E/$24D092, $24D0A6/$24D0AE/$24D0C2 and "
                       "$24D0D6 -- $24CFBA..$24D12D"),
    # TWO tables of TWENTY, not one of thirty-two: `$2546BA lea ($254712,PC)`
    # for P1 and `$2546FA lea ($254762,PC)` for P2, $50 apart.  The index is
    # `type & $1F`, which runs to 31, so the window has to cover the overrun
    # into $2547B2's code as well -- and it does, because a read there is a
    # LOUD NAMED THROW out of the dispatch, not a silent zero.
    (0x254710, 0x00C0, "W45 THE BEAM: the segment dispatches $254712 (P1, 20 "
                       "entries) and $254762 (P2, 20), read by $254680 with "
                       "`type & $1F`"),
    # THE PODS' SHOT SPAWN, $24D480.  `movea.l $8127E8,A1 / move.w (A1),D4` --
    # a ROM pointer held in RAM.  MEASURED $255278 in the shipped seed, i.e. a
    # word out of the per-power BURST-COUNT table that begins after $255042's
    # `rts` at $255158.  The window is the whole run of it up to the WAVE-12
    # ship-table window at $255330, because nothing in this port advances the
    # cursor and its extent is therefore unproven from a run.
    (0x255158, 0x01D8, "W45: $24D4B2's burst-count table, reached through the "
                       "RAM pointer $8127E8/$8127F0 (MEASURED $255278)"),
    # $23F508 is the emitter stub every segment handler and the beam draw end
    # with, and `src/spritequeue.js resolveEmitStub` READS ITS CODE to learn
    # which bucket it feeds and which calling convention it uses, rather than
    # trusting a number in a comment.  It is W36's fifth prologue shape
    # (`addi.w #$C,<ctr>` BEFORE the record read), so the resolver needs 22
    # bytes of it.
    (0x23F500, 0x0020, "W45: the emitter stub $23F508, read by "
                       "spritequeue.js resolveEmitStub"),
])

# ============= W53 (E5a): THE SHOT'S IMPACT SPARK -- POOL E's DATA ===========
#
# `src/spark.js` ports $289F54 (the allocator) and $28A098 (the driver).  Two
# windows, and BOTH ENDS OF BOTH ARE PINNED BY SOMETHING THAT IS NOT A READING:
#
#   $28A5AC..$28AB85, 1,498 B, ONE contiguous block of three things:
#       $28A5AC          template 0                              22 B
#       $28A5C2          THE DESCRIPTOR LIST, 36 longwords       144 B
#                        ($22CA1C..$22CBC0 step $C) -- and $28A5C2 + 144 lands
#                        EXACTLY on $28A652, where template 1 starts
#       $28A652..$28A785 templates 1..14, stride 22              308 B
#                        ...and $28A770 + 22 == $28A786          EXACT
#       $28A786..$28AB85 the 256-entry POINTER TABLE              1,024 B
#                        $289F68 reads it with `move.w $803916,D5 / add.w D5,D5
#                        / add.w D5,D5` -- NO MASK, exactly like $242FDE -- so
#                        it must be 256 entries, and [M] $28A786 + 256*4 ==
#                        $28AB86, which disassembles to `addq.b #1,$803917`,
#                        i.e. CODE.  EXACT, and it is the far end.
#       [M] the 256 entries resolve to 15 DISTINCT templates (one named 32
#       times, fourteen named 16), and all 15 differ ONLY in the starting
#       animation cursor: $8C $80 $74 $68 $5C $50 $44 $38 $2C $20.
#
#   $28ABFA..$28AC39, 64 B, $28ABE0's draw table (`moveq #$3f` masks the index).
#       [M] $28ABFA + 64 == $28AC3A == `lea $81DB90,A0`, code.  EXACT.
#
# NOT EXPORTED, and named rather than skipped: $28A506's template and its own
# 36-longword list at $28A51C ($22C6BC..$22C860).  They belong to $289F96 /
# $289FC0 / $289FDA -- the LASER's three pool-E producers, which this wave does
# not port.  Exporting data for a routine that does not exist is E2's $268594.
SHOT_WINDOWS.extend([
    (0x28A5AC, 0x05DA, "W53 POOL E: the 15 spark templates, their shared "
                       "36-entry descriptor list $28A5C2, and the 256-entry "
                       "pointer table $28A786 -- $28A5AC..$28AB85, whose far "
                       "end is $28AB86 (`addq.b #1,$803917`, code)"),
    (0x28ABFA, 0x0040, "W53 POOL E: $28ABE0's 64-byte draw table $28ABFA "
                       "(indexed by $803916 & $3F), read by $28A39E for the "
                       "spark's heading -- far end $28AC3A is code"),
])

# WAVE 12.  The option pods move through the SAME $241812 the ship does, with a
# speed index that comes out of the option template rather than out of the
# player record.  MEASURED $E0 = 224 -- far outside the player's own 0..31 -- and
# the port threw `speed index 224 was not exported` on the first pod move.  The
# level set is DERIVED from the templates rather than widened by hand, exactly as
# wave 8 derived the shot templates' levels.
#
# The copy at $24C0E8..$24C116 writes template bytes into record offsets +$06..
# +$21 and +$26..+$63 with a FOUR-BYTE HOLE at +$22..+$25 ($24C0F6 addq.w #4,A1),
# so the record offset a template byte lands at is:
#     off < 0x22 : rec = off + 6          (the first 7 longs)
#     off >= 0x22: rec = off + 10         (the 15 longs and the trailing word)
# Pod 0's speed index is record +$1A and pod 1's is +$3A.
OPT_TEMPLATES = 0x24BBAA
OPT_FORMATIONS = (2, 4, 6)
OPT_TEMPLATE_LEN = 90
OPT_DEPLOY_TABLE = 0x24C928     # $24C94A lea ($24C928,PC),A0
OPT_DEPLOY_ENTRIES = 6          # (formation-2) + (0 or 6), as a BYTE index


def _tmpl_off(rec: int) -> int:
    """Template byte offset for option-record offset `rec` (see above)."""
    return rec - 6 if rec < 0x26 else rec - 10


def option_templates(d: bytes) -> dict:
    out = {}
    for form in OPT_FORMATIONS:
        # $24C0D6 move.w ($5a,A4),D0 / subi.w #$2,D0 / add.w D0,D0
        a = u32(d, OPT_TEMPLATES + (form - 2) * 2)
        out[a] = list(d[a:a + OPT_TEMPLATE_LEN])
    return out


def option_speed_indices(d: bytes) -> list[int]:
    """Every ($1a,A6) an option pod can hold, derived from the ROM.

    THE TEMPLATE IS NOT THE ANSWER, and finding that out is why this function
    exists.  All three templates carry ($1a,A6) = 0; the LIVE value measured on
    the board is $E0 = 224.  The difference is the DEPLOY RAMP at `$24C934`:

      24c934: addq.b #8,($1a,A6)          <-- eight per frame, from 0
      24c938: move.w ($58,A4),D1 / beq / moveq #$6,D1      ship 0 -> 0, else 6
      24c940: move.w ($5a,A4),D0 / subi.w #$2,D0 / add.w D1,D0
      24c94a: lea ($24C928,PC),A0 / move.w (A0,D0.w),D0    a BYTE index
      24c952: cmp.b ($1a,A6),D0 / bne
      24c958: move.b #$3,($1,A6)          <-- ...and bit 1 is "deployed"

    so a pod's speed index visits 0, 8, 16, ... up to its formation's entry in
    `$24C928` and then stops there.  MEASURED entries: $E0 $E0 $F0 $E8 $E8 $F8.
    Ship 0 / formation 2 tops out at $E0 = 224, which is exactly the live value.
    """
    tops = [u16(d, OPT_DEPLOY_TABLE + 2 * i) for i in range(OPT_DEPLOY_ENTRIES)]
    for v in tops:
        if v % 8:
            raise SystemExit(f"$24C928 entry ${v:04X} is not a multiple of 8, so "
                             f"$24C934's `addq.b #8` ramp can never equal it and "
                             f"the pod would never deploy -- re-read the table")
    s = {t[_tmpl_off(rec)] for t in option_templates(d).values()
         for rec in (0x1A, 0x3A)}
    s.update(range(0, max(tops) + 1, 8))
    return sorted(s)

# $249C3E/$249C88: `lea $2554EA,A1 / movea.l (A1,D0.w),A1` with
# D0 = ((form-2)*4) + 4 if laser.  Only formation 2 (MEASURED: ($5a,A6) = 2 on
# every frame of stage1-open) and its laser twin are reachable without the
# formation code, so the walk below covers entries 0 and 1 of each table and
# says so rather than pretending to enumerate all formations.
# $25551A is the THIRD table of the same shape.  The player's own spawn never
# reads it ($249C3E/$249C88 use the first two), but the OPTION PODS' shots --
# created by the unported $24D484 into slots 0..12 of the SAME 36-slot table --
# are driven by the SAME four handlers, and a seeded pod shot carries a speed
# index ($1a,A6) out of these templates.  MEASURED: the port threw
# `speed index 68 was not exported` on the first pod shot in the seed.  So the
# walk covers it, and the reason is here rather than in a widened constant.
# ...and $24D2FC/$24D35C are the OPTION PODS' own pair, read at $24D4E2 with
# the same (ship*4 [+4 laser]) index and the same power*2 sub-index.  Their
# templates carry speed indices 68, 80, 88, 96, 120 and 168, none of which the
# player's own templates use, and a seeded pod shot is driven by the SAME four
# handlers this wave translated -- so the port needs those quadrant tables even
# though it never creates a pod shot.  MEASURED: the port threw
# `speed index 68 was not exported` twice before this line existed.
SPAWN_PTR_TABLES = [0x2554EA, 0x255502, 0x25551A, 0x24D2FC, 0x24D35C]
SPAWN_FORMATION_ENTRIES = 2      # entry 0 = shot, entry 1 = laser
SPAWN_POWERS = 5                 # power word 0,2,4,6,8 -> byte index 0,4,8,12,16
TEMPLATE_LEN = 0x26              # $24A222 consumes exactly 38 bytes from A1
TEMPLATE_SPEED_OFF = 26          # ...and byte 26 lands in ($1a,A6), the speed index
PLAYER_SPEED_LEVELS = 32         # the player's own range: floor 12, base 22, 28 held
# W31: speed indices an ENEMY HANDLER hands $241D34 as an immediate.  0x70 is
# `move.w #$70,D0` at $26B3B2 and $26B3F8, the midboss's two arm-vector reads.
HANDLER_SPEED_INDICES = {0x70}

# ======================= W36: THE ENEMY SPEED LEVELS ========================
# The set above covers the PLAYER's range and the templates the player's own
# spawner copies.  It never covered the ENEMIES, and until W36 nothing noticed,
# because every enemy handler the port had either drove position through the
# movement stream (whose SPEED operands all land inside 0..31) or did not drive
# it at all.
#
# W36's `$26AD28` (type $0B) does BOTH of the things that break that: its
# initial `($1A,A6)` comes from the sub-record PROTOTYPE `$2637A2` copies, not
# from the stream, and its handler then RAMPS that byte.  MEASURED: the port
# threw `speed index 36 was not exported` on the first live type $0B, and 36 is
# byte +$16 of the long-form prototype at `$26AD0C` -- the cartridge's own
# number, arrived at through code the port has had since W23.
#
# So the set is enumerated in three parts, all from the ROM:
STAGE1_SCRIPT = 0x230C6C          # 8-byte records, $FFFF terminator
TYPE_TAB_LO, TYPE_TAB_HI = 0x267824, 0x27E412
MOVE_AUX, MOVE_RES, MOVE_RES_END, MOVE_N = 0x23170C, 0x231852, 0x2325D0, 163
PROTO_COPY = 0x2637A2             # the loader whose two forms src/enemyproto.js
PROTO_LONG_SPEED = 0x16           # ...documents: 28 table bytes -> $20 record
PROTO_SHORT_SPEED = 0x0E          # ...16 table bytes -> $20 record
# The RAMP CEILINGS, by ROM site.  These three handlers are the only stage-1
# code that steps `($1A,A6)` arithmetically, and each does it between 0 and a
# constant it compares against:
#   $26A69C subq.b #$1  / $26A420 addq.b #$1 until `$26A40C cmpi.b #$1C`  ($08)
#   $26A958 subq.b #$1  / $26A99E addq.b #$2 until `$26A98A cmpi.b #$20`  ($09)
#   $26AE1C subq.b #$1  / $26AEEA addq.b #$1 until `$26AED6 cmpi.b #$1C`  ($0B)
# so every integer from 0 up to the larger of (that type's prototype speed, its
# ceiling) is reachable, and the closure below is `range(0, max + 1)`.
RAMP_CEILINGS = {0x1C, 0x20}


def stage1_types(d: bytes) -> set[int]:
    """The types stage 1's script names, plus the three an ENEMY spawns."""
    out = {0x1C, 0x1E, 0x23}
    a = STAGE1_SCRIPT
    while u16(d, a) != 0xFFFF:
        out.add(u16(d, a + 4) >> 8)
        a += 8
    return out


def _type_entry(t: int) -> int:
    return (TYPE_TAB_LO if t < 0x80 else TYPE_TAB_HI - 0x80 * 8) + t * 8


def proto_speed_indices(d: bytes) -> set[int]:
    """Every sub-record prototype speed byte a stage-1 type spawns with.

    Finds each init body's `lea <proto>(pc),A0 / nop / jsr $2637A2` and decodes
    the prototype the way src/enemyproto.js does -- the word-0 SIGN picks the
    form, and both forms produce $20 record bytes from 28 or 16 table bytes.
    The sub-record count is the init STUB's own `move.w #$N,($4,A5)`, i.e. N+1
    records (the `dbra`)."""
    out: set[int] = set()
    for t in sorted(stage1_types(d)):
        init = u32(d, _type_entry(t))
        n = u16(d, init + 2)
        body = init + 8
        for off in range(0, 0x200, 2):
            a = body + off
            if (u16(d, a) == 0x41FA and u16(d, a + 4) == 0x4E71
                    and u16(d, a + 6) == 0x4EB9 and u32(d, a + 8) == PROTO_COPY):
                disp = struct.unpack_from(">h", d, a + 2)[0]
                cur = (a + 2 + disp) & 0xFFFFFF       # lea's PC is the operand word
                for _ in range(n + 1):
                    if u16(d, cur) & 0x8000:          # $2637AC, the LONG form
                        out.add(d[cur + PROTO_LONG_SPEED])
                        cur += 28
                    else:                             # $2637C2, the SHORT form
                        out.add(d[cur + PROTO_SHORT_SPEED])
                        cur += 16
    return out


def stream_speed_indices(d: bytes) -> set[int]:
    """Every SPEED operand in stage 1's 163 movement streams (`>= $C0` -> the
    next byte lands in `($1A,A6)`, `$26392C`).  The opcode lengths are the ones
    src/movement.js's twelve escapes consume."""
    aux = [u16(d, MOVE_AUX + 2 * i) for i in range(MOVE_N)]
    starts = [MOVE_RES + a for a in aux]
    lens = [(starts[i + 1] - starts[i]) if i + 1 < MOVE_N
            else MOVE_RES_END - starts[i] for i in range(MOVE_N)]
    esc_len = {0: 2, 1: 2, 2: 2, 3: 2, 4: 2, 5: 6, 6: 6, 7: 2, 8: 2, 9: 2,
               10: 1, 11: 1}
    out: set[int] = set()
    for st, ln in zip(starts, lens):
        j = 4                                          # the 4-byte X,Y header
        while j < ln:
            b = d[st + j]
            if b < 0x80:
                j += 2                                 # HEAD + its param
            elif b < 0xC0:
                j += esc_len[b & 0x0F]
            else:
                out.add(d[st + j + 1])                 # $26392C move.b (A0)+,($1a,A6)
                j += 2
    return out


def enemy_speed_indices(d: bytes) -> set[int]:
    """The closure: the prototypes, the streams, and the ramps between them."""
    protos = proto_speed_indices(d)
    streams = stream_speed_indices(d)
    top = max(protos | streams | RAMP_CEILINGS)
    return protos | streams | set(range(0, top + 1))


def u16(d: bytes, a: int) -> int:
    return struct.unpack_from(">H", d, a)[0]


def u32(d: bytes, a: int) -> int:
    return struct.unpack_from(">I", d, a)[0]


def i32(d: bytes, a: int) -> int:
    return struct.unpack_from(">i", d, a)[0]


def speed_levels(d: bytes) -> int:
    """How many speed levels the pointer table holds.

    NOT a guess: entry s must be exactly $200D20 + $208*s.  The count is where
    that stops holding.  WAVE 4 scanned to 64 and said so ("a SCAN CAP, not the
    end of the table"); WAVE 8 needs index 232 (the laser template's ($1a,A6))
    and re-ran the scan with the cap at 256.  MEASURED: the pattern holds for
    EXACTLY 256 entries -- $200920+4*256 and the two longs after it are zero,
    and the last table ends at $221520 -- so 256 is now the table's END and not
    a cap.  The verifier below asserts both halves of that.
    """
    base = u32(d, SPEED_PTRS)
    n = 0
    while n < SCAN_CAP and u32(d, SPEED_PTRS + 4 * n) == base + QUAD_STRIDE * n:
        n += 1
    return n


def spawn_templates(d: bytes) -> dict:
    """Walk $2554EA/$255502 exactly as $249BFC does and return the reachable
    38-byte templates keyed by ROM address.  This is a MEASUREMENT of what the
    spawn can read, not a guess at a table length: the walk is the ROM's own
    indexing arithmetic."""
    out = {}
    for tbl in SPAWN_PTR_TABLES:
        for form in range(SPAWN_FORMATION_ENTRIES):
            per_power = u32(d, tbl + 4 * form)
            for pw in range(SPAWN_POWERS):
                # $249C48 `move.w ($20,A6),D0 / add.w D0,D0 / movea.l (A1,D0.w),A1`
                # -- power word 0,2,4,6,8 becomes byte index 0,4,8,12,16.
                t = u32(d, per_power + 4 * pw)
                out[t] = list(d[t:t + TEMPLATE_LEN])
    return out


def speed_index_set(d: bytes) -> list[int]:
    """The speed levels the port can actually reach: the player's own 0..31 plus
    every ($1a,A6) byte in a reachable spawn template.  Exporting all 256 levels
    would put 133 KiB of quadrant tables into the published bundle for levels
    nothing reads; exporting a GUESSED subset would make the port read
    `undefined`.  So the set is derived, listed in the JSON, and the port throws
    by name on any index outside it."""
    s = set(range(PLAYER_SPEED_LEVELS))
    for t in spawn_templates(d).values():
        s.add(t[TEMPLATE_SPEED_OFF])
    # WAVE 12: and the OPTION PODS' own levels, from $24BBAA's templates.
    s.update(option_speed_indices(d))
    # W31: and the levels enemy handlers pass to $241D34 as an IN-CODE CONSTANT
    # rather than out of a template, which the walk above cannot see.  The
    # midboss's arm kinematics ($26B304) does `move.w #$70,D0` at BOTH
    # $26B3B2 and $26B3F8.  Listed with its call sites, exactly as W12 listed
    # the pods' 224 -- MEASURED: the port threw `speed index 112 was not
    # exported` on the first midboss frame before this line existed.
    s.update(HANDLER_SPEED_INDICES)
    # W36: and the ENEMIES' own levels -- the sub-record prototypes, the
    # movement streams' SPEED opcodes, and the arithmetic ramps between them.
    s.update(enemy_speed_indices(d))
    return sorted(s)


def check_pool_e_extents(d: bytes) -> None:
    """W53 (E5a).  ASSERT POOL E's DATA BLOCK AGAINST THE CARTRIDGE, every export.

    Three arithmetics close exactly on a landmark that is not a reading; if any
    of them stops closing, the block has moved and the export must STOP rather
    than ship 1,498 bytes of something else.  W47 §4.3's precedent, applied to a
    table whose extent is pinned by CODE rather than by a chain.
    """
    PTRS, N_PTRS = 0x28A786, 256
    end = PTRS + N_PTRS * 4                    # $28AB86
    if d[end:end + 6] != bytes((0x52, 0x39, 0x00, 0x80, 0x39, 0x17)):
        raise SystemExit(
            f"$28A786's pointer table: this file says {N_PTRS} entries ending at "
            f"${end:06X}, but ${end:06X} is not `addq.b #1,$803917` "
            f"({d[end:end + 6].hex()}). $289F68 indexes it with an UNMASKED "
            f"$803916, so a short table reads a template out of code.")
    tpls = sorted({u32(d, PTRS + 4 * i) for i in range(N_PTRS)})
    if len(tpls) != 15:
        raise SystemExit(f"$28A786 resolves to {len(tpls)} distinct pool-E "
                         f"templates; W53 measured 15.")
    if tpls[0] != 0x28A5AC or tpls[-1] + 22 != PTRS:
        raise SystemExit(
            f"the pool-E templates run ${tpls[0]:06X}..${tpls[-1] + 22:06X}; "
            f"W53 measured $28A5AC..${PTRS:06X} (the last template abutting the "
            f"pointer table EXACTLY).")
    lists = {u32(d, t + 0x10) for t in tpls}
    if lists != {0x28A5C2}:
        raise SystemExit(f"the 15 pool-E templates name descriptor lists "
                         f"{[hex(x) for x in sorted(lists)]}; W53 measured all "
                         f"fifteen naming $28A5C2 alone.")
    # The list's own length is pinned from BOTH ends: the largest starting cursor
    # any template carries ($8C -> 36 longwords) and the next template's base.
    cur = max(u16(d, t + 0x0E) for t in tpls)
    if 0x28A5C2 + (cur // 4 + 1) * 4 != 0x28A652:
        raise SystemExit(
            f"$28A5C2 + (${cur:04X}/4 + 1) longwords does not land on $28A652, "
            f"the first template of the run. The descriptor list and the "
            f"templates no longer abut.")
    # $28ABE0's draw table: `moveq #$3f` -> 64 bytes, and $28AC3A is code.
    if d[0x28AC3A:0x28AC40] != bytes((0x41, 0xF9, 0x00, 0x81, 0xDB, 0x90)):
        raise SystemExit("$28ABFA's 64-byte draw table does not end at $28AC3A "
                         "(`lea $81DB90,A0`).")


def build(d: bytes) -> dict:
    check_pool_e_extents(d)                    # W53 -- see the function's docstring
    n = speed_levels(d)
    base = u32(d, SPEED_PTRS)
    levels = speed_index_set(d)
    quads = {}
    for s in levels:
        a = base + QUAD_STRIDE * s
        quads[str(s)] = [[i32(d, a + 8 * i), i32(d, a + 8 * i + 4)]
                         for i in range(QUAD_ENTRIES)]

    def anim(tbl: int, idx: int) -> list[list[int]]:
        # LITERALLY as the ROM addresses it: `move.w ($58,A6),D0 / add.w D0,D0 /
        # movea.l (A0,D0.w),A0`.  Note the consequence, which is why only index
        # 0 is exported: with ($58,A6) = 1 the longword read is at tbl+2 and
        # lands MIDWAY through the first pointer.  The two pointers here are 4
        # bytes apart, so the ship selector must be 0 or 2, not 0 or 1 -- and
        # ($58,A6) was MEASURED to be 0 for TYPE-A over the whole corpus.
        # TYPE-B was never exercised, so the port throws rather than guess.
        ptr = u32(d, tbl + idx * 2)
        return [[u16(d, ptr + t), u16(d, ptr + t + 2)]
                for t in range(TILT_MIN, TILT_MAX + 1, TILT_STEP)]

    return {
        "_note": ("ROM-DERIVED. Regenerate with games/ddpdoj/tools/export-tables.py. "
                  "Never commit this file."),
        "set": "ddpdojblk", "build": "B",
        "image_sha256": hashlib.sha256(d).hexdigest(),
        "dirTable": {"rom": f"${DIR_TABLE:06X}",
                     "bytes": list(d[DIR_TABLE:DIR_TABLE + 16])},
        "foldTable": {"rom": f"${FOLD_TABLE:06X}",
                      "words": [u16(d, FOLD_TABLE + 2 * i) for i in range(256)]},
        "knockback": {"rom": f"${KNOCKBACK:06X}",
                      "words": [u16(d, KNOCKBACK + 2 * i) for i in range(8)]},
        "speed": {"rom": f"${SPEED_PTRS:06X}", "levels": n,
                  "quadBase": f"${base:06X}", "quadStride": QUAD_STRIDE,
                  "quadEntries": QUAD_ENTRIES, "exported": levels,
                  "quads": quads},
        # WAVE 8 -- the shot subsystem.  See SHOT_WINDOWS.
        "rom": {"_note": ("ROM WINDOWS, read by src/rom.js the way the 68000 "
                          "reads them.  A read outside every window is a LOUD "
                          "NAMED THROW carrying the address, never undefined."),
                "windows": [{"base": f"${a:06X}", "len": ln, "why": why,
                             "hex": d[a:a + ln].hex()}
                            for a, ln, why in SHOT_WINDOWS]},
        "shot": {"spawnPtrTables": [f"${a:06X}" for a in SPAWN_PTR_TABLES],
                 "templates": {f"${a:06X}": v
                               for a, v in sorted(spawn_templates(d).items())}},
        "gov": {k: {"rom": f"${a:06X}",
                    "words": [u16(d, a + 2 * i) for i in range(n)]}
                for k, (a, n) in GOV_TABLES.items()},
        # WAVE 12 -- `b` KEPT ITS KEY AND LOST ITS NAME.  $2553CA -> $2553F2 is
        # the ship's X HALF-EXTENTS indexed by the tilt (10-recon-combat §3,
        # `$2459D0 add.w ($14,A4),D2 / sub.w ($16,A4),D3`), not a second
        # animation table.  It is emitted TWICE for one release -- under the old
        # `b` so an unregenerated rip/ still loads, and under `hitX`, which is
        # what src/vectors.js reads -- and the verifier below asserts they are
        # identical.  MEASURED, all 17 entries (+X/-X): (0000,0080) at tilt -$20,
        # (0080,0080) at 0, (0080,0000) at +$20; build A's twin $1549AE holds
        # $00C0 where this holds $0080, which is the Black Label 2/3 hitbox.
        "anim": {"tiltMin": TILT_MIN, "tiltStep": TILT_STEP,
                 "a": {"rom": f"${ANIM_A:06X}", "shipSel0": anim(ANIM_A, 0)},
                 "b": {"rom": f"${ANIM_B:06X}", "shipSel0": anim(ANIM_B, 0)},
                 "hitX": {"rom": f"${ANIM_B:06X}", "reads": "$2459E4/$2459E8",
                          "shipSel0": anim(ANIM_B, 0)}},
        # WAVE 12 -- the OPTION templates, walked the way $24C0D2 walks them.
        "option": {"templateTable": f"${OPT_TEMPLATES:06X}",
                   "formations": list(OPT_FORMATIONS),
                   "templateLen": OPT_TEMPLATE_LEN,
                   "speedIndices": option_speed_indices(d),
                   "templates": {f"${a:06X}": v
                                 for a, v in sorted(option_templates(d).items())}},
    }


def verify(t: dict) -> list[str]:
    """The invariants the PORT depends on.  A table that silently changed shape
    must stop the port, not feed it plausible numbers."""
    bad = []
    dt = t["dirTable"]["bytes"]
    if len(dt) != 16:
        bad.append("dirTable is not 16 bytes")
    for i, v in enumerate(dt):
        if v != 0xFF and (v & 0x07):
            bad.append(f"dirTable[{i}]=${v:02X} is not a multiple of 8")
    fold = t["foldTable"]["words"]
    if len(fold) != 256:
        bad.append("foldTable is not 256 words")
    # the triangle: index a*4 for a in 0..63 must fold into [0, $200]
    for a in range(64):
        if not 0 <= fold[a * 4] <= 0x200:
            bad.append(f"foldTable[{a * 4}]=${fold[a * 4]:04X} escapes the quadrant")
    sp = t["speed"]
    if sp["levels"] < 29:
        bad.append(f"only {sp['levels']} speed levels, but index 28 is MEASURED in "
                   f"use (Button 2 held; see 04-impl worklog)")
    if sp["levels"] >= SCAN_CAP:
        bad.append(f"the $200920 pattern still holds at the scan cap {SCAN_CAP} -- "
                   f"raise it; 'levels' is not the table's end")
    for k, q in sp["quads"].items():
        if len(q) != QUAD_ENTRIES:
            bad.append(f"speed {k}: {len(q)} entries, expected {QUAD_ENTRIES}")
            continue
        if q[0][1] != 0 or q[-1][0] != 0:
            bad.append(f"speed {k}: quadrant does not run (r,0)..(0,r): "
                       f"{q[0]} .. {q[-1]}")
    if sp["quads"]["0"] != [[0, 0]] * QUAD_ENTRIES:
        bad.append("speed level 0 is not all zeros -- it is the game's 'do not move'")
    for lv in sp["exported"]:
        if str(lv) not in sp["quads"]:
            bad.append(f"speed level {lv} is listed as exported and is not present")
    # WAVE 8: the ROM windows must cover every template the spawn walk found,
    # or the port would throw on its first shot on someone else's machine.
    wins = [(int(w["base"].lstrip("$"), 16), w["len"]) for w in t["rom"]["windows"]]

    def covered(a: int, n: int) -> bool:
        return any(b <= a and a + n <= b + ln for b, ln in wins)

    for k, v in t["shot"]["templates"].items():
        a = int(k.lstrip("$"), 16)
        if len(v) != TEMPLATE_LEN:
            bad.append(f"template {k}: {len(v)} bytes, expected {TEMPLATE_LEN}")
        if not covered(a, TEMPLATE_LEN):
            bad.append(f"template {k} is not inside any exported ROM window")
        if str(v[TEMPLATE_SPEED_OFF]) not in sp["quads"]:
            bad.append(f"template {k} wants speed level {v[TEMPLATE_SPEED_OFF]}, "
                       f"which was not exported")
    for w in t["rom"]["windows"]:
        if len(w["hex"]) != w["len"] * 2:
            bad.append(f"ROM window {w['base']} is {len(w['hex']) // 2} bytes, "
                       f"the manifest says {w['len']}")
    for k, (a, n) in GOV_TABLES.items():
        if len(t["gov"][k]["words"]) != n:
            bad.append(f"gov table {k} is not {n} words")
    for k in ("a", "b", "hitX"):
        n = len(t["anim"][k]["shipSel0"])
        if n != (TILT_MAX - TILT_MIN) // TILT_STEP + 1:
            bad.append(f"anim {k}: {n} tilt entries, expected 17")
    if t["anim"]["hitX"]["shipSel0"] != t["anim"]["b"]["shipSel0"]:
        bad.append("anim.hitX and the legacy anim.b disagree -- they are the "
                   "same $2553F2 read twice and must stay byte-identical")
    # WAVE 12: the ship's X half-extents are a MONOTONE pair over the tilt --
    # +X grows from 0 to $80 as the tilt goes -$20..0 and -X shrinks $80..0 as it
    # goes 0..+$20 -- and both are 0 at exactly one end.  This is the shape the
    # port's `anim()` indexing depends on, and it is asserted rather than
    # assumed: a table that changed shape must stop the export, not feed the
    # collision test plausible numbers.
    hx = t["anim"]["hitX"]["shipSel0"]
    mid = len(hx) // 2
    if hx[mid] != [0x80, 0x80]:
        bad.append(f"anim.hitX at tilt 0 is {hx[mid]}, expected [128, 128] -- "
                   f"the BLACK LABEL 4-px-wide box (build A's $1549AE has "
                   f"[192, 192], the 6-px original)")
    if hx[0][0] != 0 or hx[-1][1] != 0:
        bad.append(f"anim.hitX ends are {hx[0]} .. {hx[-1]}, expected the +X "
                   f"half to start at 0 and the -X half to end at 0")
    # ...and the option templates must be inside a window, same rule as wave 8's.
    for k, v in t["option"]["templates"].items():
        a = int(k.lstrip("$"), 16)
        if len(v) != OPT_TEMPLATE_LEN:
            bad.append(f"option template {k}: {len(v)} bytes, expected "
                       f"{OPT_TEMPLATE_LEN}")
        if not covered(a, OPT_TEMPLATE_LEN):
            bad.append(f"option template {k} is not inside any exported window")
    for lv in t["option"]["speedIndices"]:
        if str(lv) not in sp["quads"]:
            bad.append(f"option template wants speed level {lv}, not exported")
    # ----------------------------------------------------------- WAVE 21
    # The four bullet tables, checked through the EXPORTED BYTES rather than
    # through the image, so a window that is short or misaligned fails HERE and
    # not on a player's machine.  Every check is a property the port depends on
    # and none of them is "the numbers I happened to read".
    def win(a: int, n: int) -> bytes | None:
        for w in t["rom"]["windows"]:
            b = int(w["base"].lstrip("$"), 16)
            if b <= a and a + n <= b + w["len"]:
                o = (a - b) * 2
                return bytes.fromhex(w["hex"][o:o + n * 2])
        return None

    def w16(a):
        b = win(a, 2)
        return None if b is None else struct.unpack(">H", b)[0]

    def w32(a):
        b = win(a, 4)
        return None if b is None else struct.unpack(">I", b)[0]

    tps = [w32(0x281956 + 4 * k) for k in range(39)]
    if any(p is None for p in tps):
        bad.append("the $281956 template pointer table is not fully inside a window")
    else:
        if w32(0x281956 + 4 * 39) != 0x018100:
            bad.append(f"$281956[39] is ${w32(0x281956 + 4 * 39):08X}, expected "
                       f"$00018100 -- the table's far end has moved and the "
                       f"39-kind extent is no longer pinned")
        for k, p in enumerate(tps):
            if win(p, 0x12) is None:
                bad.append(f"template {k} at ${p:06X} is not inside a window")
            elif w16(p + 0x0E) != 20:
                bad.append(f"template {k} base speed is {w16(p + 0x0E)}, not 20 -- "
                           f"all 39 are 20 and src/bullets.js's speed arithmetic "
                           f"starts from that")
            elif (w16(p) & 0x3F) != k and k not in (14, 15):
                bad.append(f"template {k}'s type word ${w16(p):04X} has low 6 bits "
                           f"{w16(p) & 0x3F}; only kinds 14 and 15 are aliases "
                           f"(both carry $810A)")
    for k in range(39):
        for name, base in (("spawn-init", 0x2815C6), ("behaviour", 0x282030)):
            v = w32(base + 4 * k)
            if v is None or not (0x200000 <= v < 0x2B0000):
                bad.append(f"{name}[{k}] = {v} is missing or not a code pointer")
    fold = [w16(0x283F50 + 2 * i) for i in range(256)]
    if any(v is None for v in fold):
        bad.append("the $283F50 fold table is not fully inside a window")
    else:
        for i, v in enumerate(fold):
            m = i % 128
            want = 8 * (m if m <= 64 else 128 - m)
            if v != want:
                bad.append(f"$283F50[{i}] = {v}, expected 8*triangle = {want}")
                break
    vbase = w32(0x200920)
    for s in (0, 1, 20, 128, 255):
        if w32(0x200920 + 4 * s) != vbase + QUAD_STRIDE * s:
            bad.append(f"$200920[{s}] is not ${vbase:06X} + ${QUAD_STRIDE:X}*{s}")
    if win(vbase, 256 * QUAD_STRIDE) is None:
        bad.append("the 256 velocity quadrant tables are not fully inside a window")
    else:
        # every row runs (r,0) at quarter-angle 0 to (0,r) at 64, and speed 0 is
        # a real "do not move".  A short window would show up as a row of zeros
        # in the middle, which this catches and a length check would not.
        for s in (1, 20, 255):
            a = vbase + QUAD_STRIDE * s
            if w32(a + 4) != 0 or w32(a + 8 * 64) != 0:
                bad.append(f"velocity row {s} does not run (r,0)..(0,r)")
        if any(w32(vbase + 4 * i) != 0 for i in range(2 * QUAD_ENTRIES)):
            bad.append("velocity speed level 0 is not all zeros")
    return bad


def main() -> int:
    if not IMAGE.exists():
        raise SystemExit(f"{IMAGE} missing -- run `python tools/oracle/derive.py` first")
    d = IMAGE.read_bytes()
    t = build(d)
    bad = verify(t)
    for b in bad:
        print("FAIL " + b, file=sys.stderr)
    if bad:
        return 1
    print(f"  image sha256 {t['image_sha256']}")
    print(f"  dirTable   {' '.join(f'{b:02x}' for b in t['dirTable']['bytes'])}")
    print(f"  speed      {t['speed']['levels']} levels at {t['speed']['quadBase']}"
          f" stride ${t['speed']['quadStride']:X}, {QUAD_ENTRIES} entries each; "
          f"{len(t['speed']['exported'])} EXPORTED "
          f"{t['speed']['exported'][:34]}{' ...' if len(t['speed']['exported']) > 34 else ''}")
    for s in (0, 1, 22, 28, 80, 232):
        q = t["speed"]["quads"].get(str(s))
        if q:
            print(f"    level {s:3d}: 0deg=({q[0][0] >> 4},{q[0][1] >> 4})"
                  f"  45deg=({q[32][0] >> 4},{q[32][1] >> 4})"
                  f"  90deg=({q[64][0] >> 4},{q[64][1] >> 4})   [after asr.l #4]")
    print(f"  shot       {len(t['shot']['templates'])} reachable spawn templates, "
          f"{len(t['rom']['windows'])} ROM windows "
          f"({sum(w['len'] for w in t['rom']['windows'])} bytes)")
    if "--verify" in sys.argv:
        print("  VERIFY OK")
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / ".gitignore").write_text("*\n", encoding="utf8")
    p = OUT / "player.tables.json"
    p.write_text(json.dumps(t), encoding="utf8")
    print(f"  wrote {p}  ({p.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
