// The mod surface.  Master reference §10; values generated by
// tools/gen_tunables.py straight out of the ROM.

import test from 'node:test';
import assert from 'node:assert/strict';

import { DEFAULT_TUNABLES, makeTunables, SUBPX } from '../src/tunables.js';
import { u8 } from '../src/state.js';

/**
 * The exact key set DEFAULT_TUNABLES is expected to expose.  Asserted as a
 * SET, so both a silently dropped key and a silently added one fail here.
 */
const EXPECTED_KEYS = [
  // Player physics (master reference §10)
  'jumpVelocity', 'springJumpVelocity',
  'gravityRisingHeld', 'gravityRisingReleased', 'gravityFalling',
  'terminalVelocity',
  'walkSpeedMaxRight', 'walkSpeedMaxLeft',
  'waterSpeedRight', 'waterSpeedLeft', 'waterGravity', 'waterTerminal',
  'overspeedDecelStep', 'turnAroundFrames', 'landingSquatFrames',
  'hitboxHalfWidth', 'hitboxHalfHeight',
  'wallJumpVelocityY', 'wallJumpVelocityX',
  'knockbackX', 'knockbackY', 'ropeSegments', 'batarangSpeed',
  // Health / damage / economy
  'startingMaxHP', 'startingLives', 'maxHPCap',
  'pickupEnergy', 'pickupBatarangs', 'pickupMaxHP',
  'invulnFrames', 'meleeDamage', 'critWindow', 'enemyStunFrames',
  'objectContactDamage', 'spikeDamage', 'bossHPBonusHard',
  'deathSequenceFrames',
  // World / camera
  'cameraLeadX', 'cameraClampLeft',
  'enemyActivationRange', 'enemyDespawnRange',
  'deathPitRow', 'startingLevel', 'soundTickTMA',
];

test('DEFAULT_TUNABLES exposes exactly the documented key set', () => {
  // Master reference §10 -- the canonical mod surface.
  const actual = Object.keys(DEFAULT_TUNABLES).sort();
  assert.deepEqual(actual, [...EXPECTED_KEYS].sort());
});

test('every tunable is a finite number', () => {
  // gen_tunables.py emits ROM bytes; a string or NaN means a broken export.
  for (const [k, v] of Object.entries(DEFAULT_TUNABLES)) {
    assert.equal(typeof v, 'number', `${k} is not a number`);
    assert.ok(Number.isFinite(v), `${k} is not finite`);
    assert.ok(Number.isInteger(v), `${k} is not an integer`);
  }
});

test('player physics values match the ROM', () => {
  const t = DEFAULT_TUNABLES;
  assert.equal(t.jumpVelocity, 0x22);              // ROM: $01A4E
  assert.equal(t.springJumpVelocity, 0x32);        // ROM: $01A4A
  assert.equal(t.wallJumpVelocityY, 0x22);         // ROM: $01DA9
  assert.equal(t.wallJumpVelocityX, 0x14);         // ROM: $027A6
  assert.equal(t.gravityRisingHeld, 1);            // ROM: $01A7D
  assert.equal(t.gravityRisingReleased, 2);        // ROM: $01A79
  assert.equal(t.gravityFalling, 3);               // ROM: $01AF4
  assert.equal(t.overspeedDecelStep, 2);           // ROM: $01D6A/$01D99
  assert.equal(t.turnAroundFrames, 0x0F);          // ROM: $0187B
  assert.equal(t.landingSquatFrames, 0x10);        // ROM: $01B3E
  assert.equal(t.hitboxHalfWidth, 0x0F);           // ROM: $0052D
  assert.equal(t.hitboxHalfHeight, 0x10);          // ROM: $00531
  assert.equal(t.knockbackX, 0x10);                // ROM: $01791
  assert.equal(t.knockbackY, 0x18);                // ROM: $017B3
  assert.equal(t.ropeSegments, 5);                 // ROM: $0195E
  assert.equal(t.batarangSpeed, 0x50);             // ROM: $019F7
});

test('terminal velocity is stored signed but must wrap to the byte $BE', () => {
  // ROM: $01AFB. The clamp at $1AFA is an UNSIGNED compare against $BE.
  assert.equal(DEFAULT_TUNABLES.terminalVelocity, -66);
  assert.equal(u8(DEFAULT_TUNABLES.terminalVelocity), 0xBE);
});

test('walk caps are $18/$E8 and are NOT the acceleration thresholds', () => {
  // ROM: $01D4C / $01D7B are the caps; $1D65 / $1D94 test $1A / $E6.
  const t = DEFAULT_TUNABLES;
  assert.equal(t.walkSpeedMaxRight, 0x18);
  assert.equal(t.walkSpeedMaxLeft, -0x18);
  assert.equal(u8(t.walkSpeedMaxLeft), 0xE8);
  assert.notEqual(u8(t.walkSpeedMaxRight), 0x1A);
  assert.notEqual(u8(t.walkSpeedMaxLeft), 0xE6);
});

test('water physics match the ROM', () => {
  const t = DEFAULT_TUNABLES;
  assert.equal(t.waterSpeedRight, 8);              // ROM: $01D48
  assert.equal(t.waterSpeedLeft, -8);              // ROM: $01D77
  assert.equal(t.waterGravity, 2);                 // ROM: $01AF0, 1 frame in 8
  assert.equal(t.waterTerminal, -12);              // ROM: $01AFF
  assert.equal(u8(t.waterTerminal), 0xF4);
});

test('health / economy values match the ROM', () => {
  const t = DEFAULT_TUNABLES;
  assert.equal(t.startingMaxHP, 0x0A);             // ROM: $00201
  assert.equal(t.startingLives, 5);                // ROM: $00207
  assert.equal(t.maxHPCap, 0x10);                  // ROM: $04D6F
  assert.equal(t.pickupEnergy, 6);                 // ROM: $04DB6
  assert.equal(t.pickupBatarangs, 10);             // ROM: $04DA0
  assert.equal(t.pickupMaxHP, 2);                  // ROM: $04D69
  assert.equal(t.invulnFrames, 90);                // ROM: $015F0
  assert.equal(t.meleeDamage, 2);                  // ROM: $026F1
  assert.equal(t.critWindow, 8);                   // ROM: $026D4
  assert.equal(t.enemyStunFrames, 0x3C);           // ROM: $026CB
  assert.equal(t.objectContactDamage, 2);          // ROM: $015E6
  assert.equal(t.spikeDamage, 4);                  // ROM: $01E21
  assert.equal(t.bossHPBonusHard, 5);              // ROM: $00D84
  assert.equal(t.deathSequenceFrames, 0x78);       // ROM: $02A01
});

test('world / camera values match the ROM', () => {
  const t = DEFAULT_TUNABLES;
  assert.equal(t.cameraLeadX, 5);                  // ROM: $01052
  assert.equal(t.cameraClampLeft, 6);              // ROM: $0105C
  assert.equal(t.enemyActivationRange, 7);         // ROM: $060AA
  assert.equal(t.enemyDespawnRange, 9);            // ROM: $011B1
  assert.equal(t.deathPitRow, 0x21);               // ROM: $01765
  assert.equal(t.startingLevel, 1);                // ROM: $001FD
  assert.equal(t.soundTickTMA, 0xBB);              // ROM: $00249
});

test('SUBPX is 16 (12.4 fixed point)', () => {
  // Master reference §4.
  assert.equal(SUBPX, 16);
});

// ---------------------------------------------------------------------------
// makeTunables
// ---------------------------------------------------------------------------

test('makeTunables() with no overrides copies every default', () => {
  const t = makeTunables();
  assert.deepEqual(t, DEFAULT_TUNABLES);
  assert.notEqual(t, DEFAULT_TUNABLES, 'must be a fresh object');
});

test('makeTunables applies overrides and leaves the rest alone', () => {
  const t = makeTunables({ jumpVelocity: 99, gravityFalling: 1 });
  assert.equal(t.jumpVelocity, 99);
  assert.equal(t.gravityFalling, 1);
  assert.equal(t.terminalVelocity, DEFAULT_TUNABLES.terminalVelocity);
  assert.equal(Object.keys(t).length, Object.keys(DEFAULT_TUNABLES).length);
});

test('makeTunables never mutates DEFAULT_TUNABLES', () => {
  const before = { ...DEFAULT_TUNABLES };
  const t = makeTunables({ jumpVelocity: 1, terminalVelocity: -1 });
  t.walkSpeedMaxRight = 123;
  t.brandNew = 7;
  assert.deepEqual({ ...DEFAULT_TUNABLES }, before);
  assert.equal(DEFAULT_TUNABLES.jumpVelocity, 0x22);
  assert.equal(DEFAULT_TUNABLES.brandNew, undefined);
});

test('two makeTunables results are independent objects', () => {
  const a = makeTunables();
  const b = makeTunables();
  a.jumpVelocity = 1;
  assert.equal(b.jumpVelocity, 0x22);
  assert.equal(DEFAULT_TUNABLES.jumpVelocity, 0x22);
});

test('makeTunables accepts unknown keys verbatim (mods may add their own)', () => {
  // docs/02-MOD-SYSTEM: mods spread over the defaults; nothing validates keys.
  const t = makeTunables({ myModThing: 42 });
  assert.equal(t.myModThing, 42);
  assert.equal(DEFAULT_TUNABLES.myModThing, undefined);
});

/**
 * Documented in master reference §10 but NOT yet on the mod surface -- these
 * numbers are still inlined in src/ (see the report). Locked in so the gap is
 * visible and closing it is a deliberate, test-updating act.
 */
const KNOWN_MISSING = [
  'wallClingLockRight',   // ROM: $01F57 ($50) -- inlined in collision.js
  'wallClingLockLeft',    // ROM: $02010 ($30) -- inlined in collision.js
  'cameraYWindowLow',     // ROM: $01083 ($15) -- inlined in camera.js
  'cameraYWindowHigh',    // ROM: $01093 ($1D) -- inlined in camera.js
  'batarangDamage',       // ROM: $03D0B
  'batarangPoolSize',     // ROM: $019AA region
  'waterDrain',           // ROM: $02E8E
];

test('the §10 params that are still inlined in src/ are absent (known gap)', () => {
  for (const k of KNOWN_MISSING) {
    assert.equal(DEFAULT_TUNABLES[k], undefined, `${k} now exists -- wire it up and update EXPECTED_KEYS`);
  }
});
