// THE PALETTE, and the reason every sprite on the page used to be the colour a
// recording froze it at.
//
// WAVE 91.  Until this wave the port modelled NO palette hardware at all.  The
// page drew every sprite through `capture.bin`'s palette RAM -- one frozen
// instant of a 161-frame recording -- and `$24150A`, the cartridge's own
// 64-byte bank upload, was a COUNTED NOTE in six source files.  W90 found that
// while chasing the owner's report that the bomb "should be bright orange with
// yellowish highlights" and is instead "a bit translucent and kinda grey"
// (`90-impl` §2).  This file is the port of the subsystem it named.
//
// ============================================================================
// 1. THE HARDWARE, both ends, read off the listing rather than from the label
// ============================================================================
//
// Palette RAM is `$A00000..$A011DF` and NOTHING writes it directly.  Everything
// writes a STAGING COPY in main RAM and sets a DIRTY FLAG; `$24133C`, called
// once a frame from `$23C454`, copies a dirty region wholesale and clears its
// flag.  [M] `python tools/oracle/w27disasm.py 24133C 241404`:
//
//   [M] 24133c  tst.w $80FA66 / beq $241384
//   [M] 241346  lea $80E886,A0 / lea $A00000,A1
//   [M] 241352  moveq #$1F,D0 / 16 x `move.l (A0)+,(A1)+` / dbra   = 2048 bytes
//   [M] 241378  move.w #$0,$80FA66 / jsr $24132A(pc)   <- 41 nops, a DMA wait
//   [M] 241384  tst.w $80FA68 / beq $2413CC
//   [M] 24138E  lea $80F086,A0 / lea $A00800,A1   ... 2048 bytes, flag $80FA68
//   [M] 2413CC  tst.w $80FA6A / beq $241404
//   [M] 2413D6  lea $80F886,A0 / lea $A01000,A1
//   [M] 2413E2  moveq #$E,D0 / 8 x move.l / dbra                  =  480 bytes
//
// SO THE THREE REGIONS ARE, in words of palette RAM, and this is the fact
// `src/web/app.js` was missing for 76 waves:
//
//   words $000..$3FF   SPRITES     <- $80E886, 32 banks x 32 entries, flag $80FA66
//   words $400..$7FF   BACKGROUND  <- $80F086, 32 banks x 32 entries, flag $80FA68
//   words $800..$8EF   TEXT/HUD    <- $80F886, 15 banks x 16 entries, flag $80FA6A
//
// The block this bundle has shipped since wave 14 -- `$227E58`, uploaded by
// `$2415E8`, checked at 1020 of 1024 against the board -- is the BACKGROUND
// third.  It contains no sprite entry.  The bomb is a sprite in bank 6.
//
// ============================================================================
// 2. `$24150A` IS ONE OF NINE, and the other eight are why the label lies
// ============================================================================
//
// [M] `$24150A` is ten instructions and it is the FOURTH entry of a family of
// nine consecutive routines that differ only in destination, length and flag.
// Reading `$24150A` alone and stopping at its `rts` gets the shape wrong,
// because `$24152E` immediately follows it and is the same routine with an
// outer `dbra`:
//
//   [M] addr      dest                       length              flag
//   [M] $24150A   $80E886 + D0*64            16 longs  = 1 bank   $80FA66
//   [M] $24152E   $80E886 + D0*64            (D1+1) banks         $80FA66
//   [M] $241556   $80E886 + D0*64             8 longs  = lo half  $80FA66
//   [M] $24157A   $80E886 + D0*64 + $20       8 longs  = hi half  $80FA66
//   [M] $2415A2   $80E886 + D0*64            (D1+1) WORDS         $80FA66
//   [M] $2415C4   $80F086 + D0*64            16 longs  = 1 bank   $80FA68
//   [M] $2415E8   $80F086 + D0*64            (D1+1) banks         $80FA68
//   [M] $2414BE   $80F886 + D0*32             8 longs  = 1 TX bank $80FA6A
//   [M] $2414E2   $80F886 + D0*32            (D1+1) TX banks      $80FA6A
//
// `D0` IS THE BANK NUMBER and `lsl.w #$6,D0` is what makes it one: 64 bytes =
// 32 xRGB555 entries = one 5-bit sprite colour bank.  (The TX pair shifts by 5,
// so a text bank is SIXTEEN entries, not 32 -- `$2414BE`, and `moveq #$E`
// upstream is what pins the region at 15 of them.)
//
// **This module implements `$24150A` and `$24133C` and NOTHING ELSE of the
// nine.** The table above is CHECKED against the cartridge on every export
// (`tools/export-tables.py check_palette_upload_family`) so that it cannot rot
// the way `docs/knowledge/02-traps.md`'s nine lying comments did; a routine
// nothing calls is not ported here on the strength of a table.
//
// [M] 161 absolute-long call sites across the nine, 152 of them `jsr $24150A`.
// The census with each site's bank and source block is
// `.scratch/w91/sites.txt`, regenerated by `.scratch/w91/sites.py`.
//
// ============================================================================
// 3. WHAT THIS PORT CAN AND CANNOT SOURCE, AND WHY THE ANSWER IS PER BANK
// ============================================================================
//
// The port starts from a SEED taken mid-stage.  Every install that ran before
// the seed instant ran on the board and not here, so a port that only executed
// the installs it reaches from now on would have 32 banks of nothing.
//
// It does not, and the reason is `catchUpObjectStream` below: the stage-1
// scroll script's OBJECT STREAM is the palette installer, its cursor is a field
// in the seed's own RAM, and the entries are the cartridge's.  [M] the seed's
// `$813196` is `$2615E6` = the stream head `$26157A` + 18 entries, so replaying
// entries 0..17 out of the cartridge reproduces exactly the banks the board had
// already installed -- 18 of them -- WITHOUT taking one byte of colour from the
// recording.  [M] the result equals the board's own palette RAM on 576 of 576
// entries, and equals the seed's own staging area byte for byte.
//
// EVERY WORD CARRIES ITS PROVENANCE.  `sourced[i]` is 1 only where a ported
// install put cartridge bytes there.  The page starts from the capture's
// palette and overwrites only those words (`mergePalette`), so a bank nothing
// has sourced stays visibly on the recording rather than silently becoming
// whatever the seed's RAM happened to hold.  Broken-and-declared, never
// fabricated.

import { unreached } from './unported.js';

/** Palette RAM as the oracle dumps it: 2,560 words from `$A00000`.  The three
 *  flush copies fill words $000..$8EF; the rest is never written by anything
 *  and stays 0 and UNSOURCED, which is what makes a read of it visible. */
export const PAL_WORDS = 2560;

/** The three staging areas and their dirty flags, all in main RAM. */
export const PALSTAGE = {
  spr: { stage: 0x80e886, dirty: 0x80fa66, dst: 0x000, words: 0x400, bankWords: 32 },
  bg: { stage: 0x80f086, dirty: 0x80fa68, dst: 0x400, words: 0x400, bankWords: 32 },
  tx: { stage: 0x80f886, dirty: 0x80fa6a, dst: 0x800, words: 0x0f0, bankWords: 16 },
};

/** `$24150A`'s own arithmetic: 32 words per bank, 32 banks in the region. */
export const SPR_BANKS = 32;
export const BANK_WORDS = 32;

/** The per-game palette hardware.  PER GAME, never a module global, for the
 *  reason `ProtLatch` is (NOTES-replay.md §2: state derives from the initial
 *  state and the input words and from nothing else). */
export class PaletteState {
  constructor() {
    /** The port's own `$A00000`. */
    this.words = new Uint16Array(PAL_WORDS);
    /** 1 where a ported install from CARTRIDGE bytes produced the word. */
    this.sourced = new Uint8Array(PAL_WORDS);
    /** ...the same, on the STAGING side, so the flush can carry it across. */
    this.stageSourced = {
      spr: new Uint8Array(PALSTAGE.spr.words),
      bg: new Uint8Array(PALSTAGE.bg.words),
      tx: new Uint8Array(PALSTAGE.tx.words),
    };
    /** Every `$24150A` this port executed, keyed by CALL SITE, with the bank
     *  and the source block.  Counted rather than logged: an install that fires
     *  once a stage and one that fires every frame must not look the same. */
    this.installs = new Map();
    this.installCount = 0;
    /** Flushes, and how many of them actually copied each region. */
    this.flushes = 0;
    this.copies = { spr: 0, bg: 0, tx: 0 };
    /** `catchUpObjectStream`'s own result, for the gate to assert on. */
    this.catchUp = null;
  }

  /** How many palette words currently come from the cartridge. */
  sourcedCount() {
    let n = 0;
    for (let i = 0; i < this.sourced.length; i++) n += this.sourced[i];
    return n;
  }

  /** The sprite banks a ported install has sourced, ascending. */
  sourcedBanks() {
    const out = [];
    for (let b = 0; b < SPR_BANKS; b++) {
      if (this.sourced[b * BANK_WORDS]) out.push(b);
    }
    return out;
  }

  report() {
    return [...this.installs.entries()]
      .sort((a, b) => b[1].n - a[1].n)
      .map(([k, v]) => `${String(v.n).padStart(5)} x ${k}`);
  }
}

/**
 * `$24150A` -- movem, `lea $80E886,A1`, `lsl.w #$6,D0`, `adda.w D0,A1`,
 * sixteen `move.l (A0)+,(A1)+`, `move.w #$1,$80FA66`.
 *
 * D0 IS NOT MASKED ON THE BOARD EITHER.  `lsl.w #$6` on a D0 of 32 addresses
 * `$80E886+$800`, which is the BACKGROUND staging area -- the board would
 * scribble on it and so would this.  The port throws by address instead of
 * clamping, because a bank number out of range means the caller resolved the
 * wrong table and a clamp would hide it (`docs/knowledge/08`; the brief's "do
 * not clamp an index to stop a throw").
 *
 * @param ram   the port's main RAM
 * @param pal   the PaletteState
 * @param d0    the bank number, D0
 * @param src   64 bytes read out of the cartridge (`rom.bytes(ptr, 64)`)
 * @param site  the ROM address of the `jsr`, for the census
 * @param why   what the site is
 */
export function install24150A(ram, pal, d0, src, site, why) {
  if (!(d0 >= 0 && d0 < SPR_BANKS)) {
    unreached(0x24150a, `$24150A was handed bank ${d0} from $${site.toString(16)
      .toUpperCase()}. lsl.w #$6 makes that $80E886+$${(d0 * 64).toString(16)
      .toUpperCase()}, which is outside the 32-bank sprite staging area and on `
      + `the board would land in the BACKGROUND staging at $80F086. The caller `
      + `resolved the wrong table; clamping would hide it`);
  }
  if (src.length !== 64) {
    unreached(0x24150a, `$24150A from $${site.toString(16).toUpperCase()} was `
      + `handed ${src.length} source bytes and it copies 16 longwords = 64. `
      + `A short read means the ROM window is narrower than the block`);
  }
  const base = PALSTAGE.spr.stage + d0 * 64;
  for (let i = 0; i < 32; i++) {
    ram.setU16(base + i * 2, (src[i * 2] << 8) | src[i * 2 + 1]);
    pal.stageSourced.spr[d0 * BANK_WORDS + i] = 1;
  }
  ram.setU16(PALSTAGE.spr.dirty, 1);                       // $241520
  const k = `$${site.toString(16).toUpperCase()} bank ${d0} <- ${why}`;
  const e = pal.installs.get(k) ?? { n: 0, bank: d0 };
  e.n++;
  pal.installs.set(k, e);
  pal.installCount++;
}

/**
 * `$24133C` -- the once-a-frame upload, called from `$23C454`.
 *
 * THE GATE AT THE CALL SITE IS NOT MODELLED AND THAT IS DELIBERATE.  `$23C44C
 * tst.b $803940 / beq $23C472` runs this block only while the vblank semaphore
 * is still armed, i.e. once per LOOP ITERATION that reached the spin.  The port
 * runs one iteration per `step()`, so calling this once at the end of `step()`
 * is the same schedule.  If the port ever models a dropped frame, this is the
 * line that has to learn about it, which is why it says so here.
 *
 * Returns which regions were copied, so a caller can tell "nothing was dirty"
 * from "the flush never ran".
 */
export function flush24133C(ram, pal) {
  const did = { spr: false, bg: false, tx: false };
  for (const key of ['spr', 'bg', 'tx']) {
    const r = PALSTAGE[key];
    if (ram.u16(r.dirty) === 0) continue;                  // $24133C/$241384/$2413CC
    for (let i = 0; i < r.words; i++) {
      pal.words[r.dst + i] = ram.u16(r.stage + i * 2);
      pal.sourced[r.dst + i] = pal.stageSourced[key][i];
    }
    ram.setU16(r.dirty, 0);                                // $241378/$2413C0/$2413F8
    did[key] = true;
    pal.copies[key]++;
  }
  pal.flushes++;
  return did;
}

/**
 * THE CATCH-UP, and it is the one thing in this file that is not a
 * transcription of an instruction.  Read the argument before the code.
 *
 * `$2620DE` (op $00 SPAWN, `src/background.js`) walks the scroll script's
 * OBJECT STREAM and hands each (pointer, param) pair to `$24150A`.  For stage 1
 * that stream is 22 entries at `$26157A` and it is the sprite palette: [M]
 * eighteen of its entries carry a `$22xxxx` colour block and a bank number.
 *
 * The port resumes mid-stage, so the entries the board consumed before the seed
 * instant will never execute here.  The cursor that says HOW MANY is a
 * longword in the seed's own RAM (`($4,A6)` of the script-0 state block at
 * `$813192`), and the stream head is a longword in the CARTRIDGE
 * (`$261FFC move.l (A2)+,$4(A1)`, A2 from the per-stage pair table `$26153E`).
 *
 * So this replays entries [head, cursor) through the SAME `$24150A` the live
 * op $00 uses.  It takes ONE number from the recording -- how far the cursor
 * had advanced -- and every byte of colour from the cartridge.  That is the
 * same bargain `bgSeed` already makes for the tilemap ring, and a weaker one:
 * `bgSeed` carries 63 columns of the board's pixels, this carries an integer.
 *
 * [M] on the shipped seed it replays 18 entries into 18 banks and the bytes it
 * writes are IDENTICAL to the ones already in the seed's staging area (`same`
 * below is 576 of 576).  That equality is the check that the model is right,
 * and `tools/webgate.mjs` asserts it.
 *
 * A stream whose cursor is not an exact multiple of 6 past its head, or which
 * hits the `$FFFFFFFF` terminator early, is a LOUD NAMED THROW: it would mean
 * the seed and the cartridge disagree about which stage this is.
 */
export function catchUpObjectStream(ram, rom, pal, opts = {}) {
  const SCRIPT_PAIR = 0x26153e;   // $26152C lea ($26153E,PC),A0
  const SCR0 = 0x813192;          // $261FF2 lea $813192,A1
  const OBJ = 0x04;               // $261FFC move.l (A2)+,$4(A1)
  const STAGE_X4 = 0x813096;      // $240D80's index into every per-stage table
  const stageX4 = ram.u16(STAGE_X4);
  const pair = rom.u32(SCRIPT_PAIR + stageX4);
  const script = rom.u32(pair);                     // script 0
  const head = rom.u32(script);
  const cursor = ram.u32(SCR0 + OBJ);
  const res = { head, cursor, entries: 0, banks: [], same: 0, total: 0, skipped: 0 };
  if (cursor === head) return (pal.catchUp = res);
  // A ZERO CURSOR IS NOT A CORRUPT ONE.  `$261FFC` is what writes this field,
  // so zero means the scroll script has never been installed at all -- which is
  // true of the board's own script-1 block in the shipped seed ($8131AE is 0 on
  // 161 of 161 recorded frames) and of every hand-built fixture in `tests/`.
  // There is nothing to replay and it is not a disagreement; it is counted, so
  // that "no palette because no script" cannot look like "no palette because
  // the catch-up silently did nothing".
  if (cursor === 0) {
    res.noScript = true;
    opts.note?.(0x261ffc, `the script-0 object cursor is 0, so $261FFC has `
      + `never run on this seed and there is no consumed prefix to replay. `
      + `Every sprite bank stays the recording's until a live install writes it`);
    return (pal.catchUp = res);
  }
  if (cursor < head || (cursor - head) % 6 !== 0) {
    unreached(0x2620fc, `the seed's script-0 object cursor is $${cursor
      .toString(16).toUpperCase()} and the cartridge's stream head for stage `
      + `$${(stageX4 / 4).toString(16)} is $${head.toString(16).toUpperCase()}. `
      + `The stream is 6-byte entries, so a cursor that is not head + 6n is not `
      + `a position in THIS stream -- the seed and the cartridge disagree about `
      + `which stage this is, and replaying anything would invent a palette`);
  }
  for (let a = head; a < cursor; a += 6) {
    const ptr = rom.u32(a);
    if (ptr === 0xffffffff) {                       // $2620E6 cmpa.l/beq
      unreached(0x2620e6, `the stage's object stream terminates at $${a
        .toString(16).toUpperCase()} but the seed's cursor is $${cursor
        .toString(16).toUpperCase()}, past the end. The seed's scroll state and `
        + `this cartridge's stream are not the same stream`);
    }
    const param = rom.u16(a + 4);
    let src;
    try {
      src = rom.bytes(ptr, 64);
    } catch (e) {
      // A pointer outside every exported window is the exporter's problem and
      // it is NAMED rather than skipped silently -- but it must not stop the
      // page, because the remaining entries are still sourceable.
      res.skipped++;
      opts.note?.(0x2620f2, `object-stream catch-up entry at $${a.toString(16)
        .toUpperCase()} points at $${ptr.toString(16).toUpperCase()}, which is `
        + `outside every ROM window: ${e.message.slice(0, 120)}`);
      continue;
    }
    // The equality check, before the write, against the staging the seed
    // carries.  It is a MEASUREMENT and never a gate on the write: a seed from
    // a different instant may legitimately disagree.
    const base = PALSTAGE.spr.stage + param * 64;
    if (param >= 0 && param < SPR_BANKS) {
      for (let i = 0; i < 32; i++) {
        res.total++;
        if (ram.u16(base + i * 2) === ((src[i * 2] << 8) | src[i * 2 + 1])) res.same++;
      }
    }
    install24150A(ram, pal, param, src, 0x2620f2,
      `$${ptr.toString(16).toUpperCase()} (object stream catch-up)`);
    res.entries++;
    if (!res.banks.includes(param)) res.banks.push(param);
  }
  res.banks.sort((a, b) => a - b);
  return (pal.catchUp = res);
}

/**
 * The page's palette: the recording's, with every CARTRIDGE-SOURCED word
 * overwritten by the port's.
 *
 * NOT the other way round, and the direction is the honest part.  A word the
 * port has not sourced keeps the capture's value and is COUNTED as such; the
 * page prints both numbers.  Silently substituting the port's zeroes -- or the
 * seed's staging, which is the board's RAM and not the cartridge -- would look
 * finished and be a recording again by a different door.
 */
export function mergePalette(pal, capPal, out) {
  const n = Math.min(capPal.length, out?.length ?? capPal.length);
  const dst = out && out.length >= n ? out : new Uint16Array(capPal.length);
  dst.set(capPal.subarray(0, n));
  let fromCart = 0;
  for (let i = 0; i < n && i < pal.sourced.length; i++) {
    if (pal.sourced[i]) { dst[i] = pal.words[i]; fromCart++; }
  }
  dst.fromCartridge = fromCart;
  return dst;
}

/** How many of the port's cartridge-sourced words equal the BOARD's own
 *  palette RAM at `capPal`.  This is the direct comparison the brief asks for:
 *  palette RAM is in the capture, so unlike a sprite's pixels it can be checked
 *  entry for entry without an emulator. */
export function agreeWithBoard(pal, capPal) {
  let sourced = 0, agree = 0;
  const perBank = new Map();
  for (let i = 0; i < capPal.length && i < pal.sourced.length; i++) {
    if (!pal.sourced[i]) continue;
    sourced++;
    const bank = i < 0x400 ? (i >> 5) : null;
    const ok = pal.words[i] === capPal[i];
    if (ok) agree++;
    if (bank !== null) {
      const e = perBank.get(bank) ?? { n: 0, ok: 0 };
      e.n++; if (ok) e.ok++;
      perBank.set(bank, e);
    }
  }
  return { sourced, agree, perBank };
}
