// Assemble the deployable site into dist/.
//
// Only what a browser needs: the launcher, src/ and the extracted assets.
// Tools, tests, docs, the disassembly and the ROM itself all stay out.
//
// dist/ is gitignored -- it contains ROM-derived data and is regenerated from
// your own cartridge with `python tools/export_assets.py` first.
//
// Usage:  node tools/build-dist.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROOT } from './oracle/_env.mjs';

const DIST = path.join(ROOT, 'dist');

// Per game: src/ and assets/. tests/ is deliberately NOT copied.
const GAMES = ['batman'];
const INCLUDE = ['index.html',
                 ...GAMES.flatMap((g) => [`games/${g}/src`, `games/${g}/assets`])];

function copy(src, dst) {
  const st = fs.statSync(src);
  if (st.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const name of fs.readdirSync(src)) copy(path.join(src, name), path.join(dst, name));
  } else {
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.copyFileSync(src, dst);
  }
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

for (const item of INCLUDE) {
  const src = path.join(ROOT, item);
  if (!fs.existsSync(src)) {
    console.error(`missing ${item} -- run: python tools/export_assets.py`);
    process.exit(1);
  }
  copy(src, path.join(DIST, item));
}

// Assets must REVALIDATE, not be treated as immutable.
//
// They were served `max-age=31536000, immutable`, which is only safe if a
// file's contents never change under a fixed URL -- and ours do: re-running an
// exporter rewrites them in place. assets/water.json gained a per-level shape
// and every browser that had already cached the old one kept it for a year,
// silently losing the window tilemap and the tile animation. The water then
// rendered as black squares, intermittently, depending purely on cache state.
//
// Cloudflare Pages sends ETags, so revalidation is a 304 in the normal case.
// If these ever need long caching again, the URLs have to carry a content
// hash first.
//
// THE ENTRY DOCUMENT IS `no-store`, NOT `no-cache`, and the distinction is the
// whole point. `no-cache` means "keep it, but revalidate" -- phones treat that
// loosely for the top-level document, and Safari's back-forward cache will
// hand back a stored page without asking anyone. That has looked like a game
// bug three separate times in this project. `no-store` leaves nothing to serve
// stale.
//
// Only the HTML pays that cost; everything it references stays on `no-cache`
// and revalidates to a 304 via ETag, which is cheap and correct once the
// document that names them is guaranteed fresh. Both `/` and `/index.html` are
// listed because a rule for one does not necessarily match the other, and the
// `/*` fallback catches anything added later.
// ORDER MATTERS AND IT IS NOT "MOST SPECIFIC WINS". Cloudflare Pages applies
// every matching rule in file order and later ones override earlier ones, so
// the broad `/*` fallback has to come FIRST. Written the other way round it
// silently reverted the entry document to no-cache -- verified by reading
// Cache-Control off the live response, which is the only way to know.
fs.writeFileSync(path.join(DIST, '_headers'), [
  '/*',
  '  Cache-Control: no-cache',
  '',
  // One rule for everything a game owns -- its src/ and its assets/ both live
  // under /games/<id>/ now, so the two separate /assets/* and /src/* rules that
  // used to be here no longer match anything and would have gone quietly dead.
  '/games/*',
  '  Cache-Control: no-cache',
  '',
  '/',
  '  Cache-Control: no-store, must-revalidate',
  '',
  '/index.html',
  '  Cache-Control: no-store, must-revalidate',
  '',
].join('\n'));

// Stamp the SAME build id into the code and into the manifest, so the app can
// tell when a browser has served it a mixed pair.
//
// `no-cache` makes every file revalidate, and every path shape does carry it --
// but that is not the failure mode. Deploys are not atomic from a client's
// point of view: a page loaded while one is landing can take new JS from one
// edge and an old manifest from another. That showed up as "cannot read
// properties of undefined (reading 'map')" on a phone while the same build was
// fine on a laptop, and no cache header can prevent it. Detecting it can.
const buildId = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
for (const g of GAMES) {
fs.writeFileSync(path.join(DIST, 'games', g, 'src', 'buildid.js'), [
  '// Generated by tools/build-dist.mjs. In a dev tree this file does not',
  '// exist, and assets.js skips the check entirely.',
  `export const BUILD_ID = '${buildId}';`,
  '',
].join('\n'));
  const mp = path.join(DIST, 'games', g, 'assets', 'manifest.json');
  const m = JSON.parse(fs.readFileSync(mp, 'utf8'));
  m.buildId = buildId;
  fs.writeFileSync(mp, JSON.stringify(m));
}

let files = 0, bytes = 0;
(function walk(d) {
  for (const n of fs.readdirSync(d)) {
    const p = path.join(d, n);
    const s = fs.statSync(p);
    if (s.isDirectory()) walk(p); else { files++; bytes += s.size; }
  }
})(DIST);

console.log(`dist/ built: ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
