#!/usr/bin/env python3
"""Generate src/tunables.js by reading the constants out of the ROM itself.

Every entry names the file offset of the operand byte in the original code, so
the generated module is provably the game's own numbers rather than values
copied by hand out of a document.  Source: docs/00-MASTER-REFERENCE.md §10.

Usage:  python tools/gen_tunables.py [--check]
        --check verifies each byte still equals the expected value and exits
        non-zero on mismatch (guards against a bad offset silently drifting).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gbrom import Rom, ROOT, GAME_ROOT

# name, file offset, expected value, signed?, unit/comment
TUNABLES = [
    ('-- Player physics', None, None, False, ''),
    ('jumpVelocity',            0x01A4E, 0x22, False, 'subpx/frame, +Y is up'),
    ('springJumpVelocity',      0x01A4A, 0x32, False, 'subpx/frame ($C751 armed)'),
    ('gravityRisingHeld',       0x01A7D, 0x01, False, 'subpx/frame^2 while A held'),
    ('gravityRisingReleased',   0x01A79, 0x02, False, 'subpx/frame^2 after A released'),
    ('gravityFalling',          0x01AF4, 0x03, False, 'subpx/frame^2'),
    ('terminalVelocity',        0x01AFB, 0xBE, True,  'signed: -66 subpx/frame'),
    ('walkSpeedMaxRight',       0x01D4C, 0x18, True,  '+1.5 px/frame'),
    ('walkSpeedMaxLeft',        0x01D7B, 0xE8, True,  '-1.5 px/frame'),
    ('waterSpeedRight',         0x01D48, 0x08, True,  ''),
    ('waterSpeedLeft',          0x01D77, 0xF8, True,  ''),
    ('waterGravity',            0x01AF0, 0x02, False, 'applied 1 frame in 8'),
    ('waterTerminal',           0x01AFF, 0xF4, True,  'signed: -12'),
    ('overspeedDecelStep',      0x01D6A, 0x02, False, 'subpx/frame when over max'),
    # Master reference cited $0187B/$018B6; those are the LDH [$FF8F] operands.
    # The real constants are the `LD A,$0F` at $01878/$018B3.
    ('turnAroundFrames',        0x01879, 0x0F, False, 'turn-stall duration'),
    ('landingSquatFrames',      0x01B3E, 0x10, False, ''),
    ('hitboxHalfWidth',         0x0052D, 0x0F, False, 'px; per-anim override at 0:$27A8'),
    ('hitboxHalfHeight',        0x00531, 0x10, False, 'px'),
    ('wallJumpVelocityY',       0x01DA9, 0x22, False, ''),
    ('wallJumpVelocityX',       0x027A6, 0x14, True,  '+/- applied by facing'),
    ('knockbackX',              0x01791, 0x10, True,  ''),
    ('knockbackY',              0x017B3, 0x18, False, ''),
    ('ropeSegments',            0x0195E, 0x05, False, ''),
    ('batarangSpeed',           0x019F7, 0x50, False, ''),

    ('-- Health, damage, economy', None, None, False, ''),
    ('startingMaxHP',           0x00201, 0x0A, False, ''),
    ('startingLives',           0x00207, 0x05, False, ''),
    ('maxHPCap',                0x04D6F, 0x10, False, ''),
    ('pickupEnergy',            0x04DB6, 0x06, False, 'HP restored'),
    ('pickupBatarangs',         0x04DA0, 0x0A, False, ''),
    ('pickupMaxHP',             0x04D69, 0x02, False, ''),
    ('invulnFrames',            0x015F0, 0x5A, False, '90 frames'),
    ('meleeDamage',             0x026F1, 0x02, False, ''),
    ('critWindow',              0x026D4, 0x08, False, '(LY^frame) < this'),
    ('enemyStunFrames',         0x026CB, 0x3C, False, ''),
    ('objectContactDamage',     0x015E6, 0x02, False, ''),
    ('spikeDamage',             0x01E21, 0x04, False, ''),
    ('bossHPBonusHard',         0x00D84, 0x05, False, 'difficulty 2'),
    ('deathSequenceFrames',     0x02A01, 0x78, False, '120 frames'),

    ('-- World and camera', None, None, False, ''),
    ('cameraLeadX',             0x01052, 0x05, False, 'metatiles ahead of player'),
    ('cameraClampLeft',         0x0105C, 0x06, False, 'metatiles'),
    ('enemyActivationRange',    0x060AA, 0x07, False, 'metatiles'),
    ('enemyDespawnRange',       0x011B1, 0x09, False, 'metatiles'),
    ('deathPitRow',             0x01765, 0x21, False, 'Y hi >= this = death'),
    ('startingLevel',           0x001FD, 0x01, False, ''),
    ('soundTickTMA',            0x00249, 0xBB, False, 'rTMA -> 4096/69 = 59.36 Hz'),
]

HEADER = '''// GENERATED by tools/gen_tunables.py -- do not edit by hand.
//
// Every value below was read out of the original ROM at the cited file offset,
// so this module is the game's own numbers, not a hand transcription.
// Re-generate with:  python tools/gen_tunables.py
//
// Units: positions and velocities are 12.4 fixed point (SUBPX = 16 per pixel).
// Velocity Y is POSITIVE UP (the game computes `Y -= VelY`).
//
// The mod system overrides these at load time; nothing else may inline them.

export const SUBPX = 16;

export const DEFAULT_TUNABLES = {
'''

FOOTER = '''};

/** Fresh mutable copy; mods mutate the copy, never DEFAULT_TUNABLES. */
export function makeTunables(overrides = {}) {
  return { ...DEFAULT_TUNABLES, ...overrides };
}
'''


def main():
    check = '--check' in sys.argv
    rom = Rom()
    lines = []
    problems = []

    for name, off, expect, signed, comment in TUNABLES:
        if off is None:
            lines.append('')
            lines.append(f'  // {name[3:]}')
            continue
        actual = rom.data[off]
        if actual != expect:
            problems.append(f'{name}: offset ${off:05X} is ${actual:02X}, '
                            f'expected ${expect:02X}')
        val = actual - 256 if (signed and actual > 127) else actual
        note = f'  // ${off:05X}'
        if comment:
            note += f' - {comment}'
        lines.append(f'  {name}: {val},{note}')

    if problems:
        print('MISMATCH between ROM and documented offsets:', file=sys.stderr)
        for p in problems:
            print('  ' + p, file=sys.stderr)
        return 1

    if check:
        print(f'ok - all {len([t for t in TUNABLES if t[1] is not None])} '
              f'tunables match the ROM')
        return 0

    out = os.path.join(GAME_ROOT, 'src', 'tunables.js')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8') as f:
        f.write(HEADER + '\n'.join(lines) + '\n' + FOOTER)
    print(f'wrote {out} ({len([t for t in TUNABLES if t[1] is not None])} constants)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
