// GENERATED by tools/gen_tunables.py -- do not edit by hand.
//
// Every value below was read out of the original ROM at the cited file offset,
// so this module is the game's own numbers, not a hand transcription.
// Re-generate with:  python tools/gen_tunables.py
//
// Units: positions and velocities are 12.4 fixed point (SUBPX = 16 per pixel).
// Velocity Y is POSITIVE UP (the game computes `Y -= VelY`).
//
// The mod system overrides these at load time; nothing else may inline them.

export const SUBPX = 16;

export const DEFAULT_TUNABLES = {

  // Player physics
  jumpVelocity: 34,  // $01A4E - subpx/frame, +Y is up
  springJumpVelocity: 50,  // $01A4A - subpx/frame ($C751 armed)
  gravityRisingHeld: 1,  // $01A7D - subpx/frame^2 while A held
  gravityRisingReleased: 2,  // $01A79 - subpx/frame^2 after A released
  gravityFalling: 3,  // $01AF4 - subpx/frame^2
  terminalVelocity: -66,  // $01AFB - signed: -66 subpx/frame
  walkSpeedMaxRight: 24,  // $01D4C - +1.5 px/frame
  walkSpeedMaxLeft: -24,  // $01D7B - -1.5 px/frame
  waterSpeedRight: 8,  // $01D48
  waterSpeedLeft: -8,  // $01D77
  waterGravity: 2,  // $01AF0 - applied 1 frame in 8
  waterTerminal: -12,  // $01AFF - signed: -12
  overspeedDecelStep: 2,  // $01D6A - subpx/frame when over max
  turnAroundFrames: 15,  // $01879 - turn-stall duration
  landingSquatFrames: 16,  // $01B3E
  hitboxHalfWidth: 15,  // $0052D - px; per-anim override at 0:$27A8
  hitboxHalfHeight: 16,  // $00531 - px
  wallJumpVelocityY: 34,  // $01DA9
  wallJumpVelocityX: 20,  // $027A6 - +/- applied by facing
  knockbackX: 16,  // $01791
  knockbackY: 24,  // $017B3
  ropeSegments: 5,  // $0195E
  batarangSpeed: 80,  // $019F7

  // Health, damage, economy
  startingMaxHP: 10,  // $00201
  startingLives: 5,  // $00207
  maxHPCap: 16,  // $04D6F
  pickupEnergy: 6,  // $04DB6 - HP restored
  pickupBatarangs: 10,  // $04DA0
  pickupMaxHP: 2,  // $04D69
  invulnFrames: 90,  // $015F0 - 90 frames
  meleeDamage: 2,  // $026F1
  critWindow: 8,  // $026D4 - (LY^frame) < this
  enemyStunFrames: 60,  // $026CB
  objectContactDamage: 2,  // $015E6
  spikeDamage: 4,  // $01E21
  bossHPBonusHard: 5,  // $00D84 - difficulty 2
  deathSequenceFrames: 120,  // $02A01 - 120 frames

  // World and camera
  cameraLeadX: 5,  // $01052 - metatiles ahead of player
  cameraClampLeft: 6,  // $0105C - metatiles
  enemyActivationRange: 7,  // $060AA - metatiles
  enemyDespawnRange: 9,  // $011B1 - metatiles
  deathPitRow: 33,  // $01765 - Y hi >= this = death
  startingLevel: 1,  // $001FD
  soundTickTMA: 187,  // $00249 - rTMA -> 4096/69 = 59.36 Hz
};

/** Fresh mutable copy; mods mutate the copy, never DEFAULT_TUNABLES. */
export function makeTunables(overrides = {}) {
  return { ...DEFAULT_TUNABLES, ...overrides };
}
